/****************************************************************************
* SISU-mikrosimulointimalli
* Copyright (C) 2013 Tilastokeskus
* Mallikoodia voi jakaa, modifioida ja hyödyntää Tilastokeskuksen yleisten
* käyttöehtojen mukaisesti,
* ks. http://www.stat.fi/org/lainsaadanto/yleiset_kayttoehdot.html tai
* LICENSE.TXT-tiedosto päähakemistossa.
******************************************************************************/

/***********************************************************
* Kuvaus: Verotuksen esimerkkilaskelmien pohja             *
* Tekijä: Filip Kjellberg / KELA		         		   *
* Luotu: 3.1.2012				       					   *
* Viimeksi päivitetty: 03.05.2012			     		   *
* Päivittäjä: Filip Kjellberg / KELA		     	  	   *
************************************************************/


/* 1. Esimerkkilaskentaa ohjaavat makromuuttujat */

%MACRO Aloitus;

%LET TYYPPI = ESIM; 			* Parametrien hakutapa, aina ESIM ;

/* Jos mallia käytetään käyttöliittymästä (&EG = 1), niin seuraavia vaiheita ei ajeta */

%IF &EG NE 1 %THEN %DO;

%LET TULOSNIMI_VE = vero_esim_&SYSDATE._1 ; * Simuloidun tulostiedoston nimi ;
%LET VALITUT =  _ALL_; 			* Tulostaulukossa näytettävät muuttujat ;

* Inflaatiokorjaus. Parametrien deflatoinnissa käytettävän kertoimen voi syöttää itse
  INF-makromuuttujaan (HUOM! desimaalit erotettava pisteellä .). Jos puolestaan haluaa käyttää automaattista 
  elinkustannusindeksiin perustuvaa parametrien muunnoskerrointa, 
  tulee INF-makromuuttujalle antaa arvoksi 999.
  Tällöin on annettava myös perusvuosi, johon aineiston lainsäädäntövuotta verrataan; 	

%LET INF = 1.00; * Syötä arvo tai 999 ;
%LET AVUOSI = 2012; * Perusvuosi inflaatiokorjausta varten ;
%LET PINDEKSI_VUOSI = pindeksi_vuosi; * Käytettävä indeksien parametritaulukko ;

* Laki- ja apumakro-ohjelmien ajon säätäminen ; 

%LET LAKIMAKROT = 1;    * Lakimakro-ohjelman ajo (1 jos ajetaan, 0 jos ei);
%LET LAKIMAK_TIED_VE = VEROlakimakrot;	* Lakimakroissa käytettävän tiedoston nimi ;
%LET APUMAKROT = 1;   	* Apumakro-ohjelman ajo (1 jos ajetaan, 0 jos ei);
%LET APUMAK_TIED_VE = VEROapumakrot; * Apumakroissa käytettävän tiedoston nimi ;
%LET EXCEL = 1; 		 * Viedäänkö tulostaulukko automaattisesti Exceliin (1 = Kyllä, 0 = Ei) ;

* Käytettävien parametritiedostojen nimet ;

%LET PVERO = pvero;
%LET PVERO_VARALL = pvero_varall; 

%END;

%MEND Aloitus;

%Aloitus;


/* 2. Tällä makrolla säädellään laki- ja apumakro-ohjelmien ajoa. 
	  Jos makrot on jo tallennettu tai otettu käyttöön, makro-ohjelmia ei ole pakko ajaa uudestaan. 
	  C-funktioita käytettäessä SASCBTBL-määritys on joka tapauksessa pakko tehdä. */

%MACRO TeeMakrot;

%IF &F = C %THEN %DO;
	FILENAME SASCBTBL "&LEVY&KENO&HAKEM&KENO.JUTTA&KENO.juttamodul.txt";
%END;

/* Ajetaan lakimakrot ja tallennetaan ne (optio) */

%IF (&LAKIMAKROT = 1 AND &F = C) %THEN %DO;
	%INCLUDE "&LEVY&KENO&HAKEM&KENO.JUTTA&KENO.juttafunkc.sas";
%END;

%ELSE %IF (&LAKIMAKROT = 1 AND &F = S) %THEN %DO;
	%INCLUDE "&LEVY&KENO&HAKEM&KENO.MAKROT&KENO&LAKIMAK_TIED_VE..sas";
%END;

/* Ajetaan apumakrot ja tallennetaan ne (optio) */

%IF &APUMAKROT = 1 %THEN %DO;
	%INCLUDE "&LEVY&KENO&HAKEM&KENO.MAKROT&KENO&APUMAK_TIED_VE..sas";
%END;

%MEND TeeMakrot;

%TeeMakrot;

/* 3. Datan generointia ohjaavat makromuuttujat */

%MACRO Generoi_Muuttujat;

/* Jos mallia käytetään käyttöliittymästä (&EG = 1), niin seuraavia vaiheita ei ajeta */

%IF &EG NE 1 %THEN %DO;

/* 3.1 Fiktiivinen data */

* Lainsäädäntövuosi (1980-);
%LET MINIMI_VERO_VUOSI = 2012;
%LET MAKSIMI_VERO_VUOSI = 2012;

* Palkkatulo (e/v);
%LET MINIMI_VERO_PTULO = 15000;
%LET MAKSIMI_VERO_PTULO = 100000; 
%LET KYNNYS_VERO_PTULO = 5000;

* Muu työtulo kuin palkkatulo (e/v);
%LET MINIMI_VERO_MTULO = 0;
%LET MAKSIMI_VERO_MTULO = 0; 
%LET KYNNYS_VERO_MTULO = 200;

* Päivärahatulo (e/v);
%LET MINIMI_VERO_PRAHATULO = 0;
%LET MAKSIMI_VERO_PRAHATULO = 0;
%LET KYNNYS_VERO_PRAHATULO = 500;

* Eläketulo (e/v);
%LET MINIMI_VERO_ETULO = 0;
%LET MAKSIMI_VERO_ETULO = 0;
%LET KYNNYS_VERO_ETULO = 500;

* Opintoraha (e/v);
%LET MINIMI_VERO_OPRAHA = 0;
%LET MAKSIMI_VERO_OPRAHA = 0;
%LET KYNNYS_VERO_OPRAHA = 100;

* Osinkotulo ansiotulona (e/v);
%LET MINIMI_VERO_OSANSTULO = 0;
%LET MAKSIMI_VERO_OSANSTULO = 0;  
%LET KYNNYS_VERO_OSANSTULO = 500;

* Muu ansiotulo (e/v);
%LET MINIMI_VERO_MUUANSTULO = 0;
%LET MAKSIMI_VERO_MUUANSTULO = 0;
%LET KYNNYS_VERO_MUUANSTULO = 500; 

* Osinkotulo pääomatulona (e/v);
%LET MINIMI_VERO_OSINKOTULO = 0;
%LET MAKSIMI_VERO_OSINKOTULO = 0;  
%LET KYNNYS_VERO_OSINKOTULO = 1000;

* Vuokratulot vakituisesta asunnosta (e/v);
%LET MINIMI_VERO_VUOKRATULO = 0;
%LET MAKSIMI_VERO_VUOKRATULO = 0;
%LET KYNNYS_VERO_VUOKRATULO = 500;

* Veronalaiset korkotulot (e/v);
%LET MINIMI_VERO_KORKOTULO = 0;
%LET MAKSIMI_VERO_KORKOTULO = 0;
%LET KYNNYS_VERO_KORKOTULO = 500; 

* Muu pääomatulo (e/v);
%LET MINIMI_VERO_MUUPOTULO = 0;
%LET MAKSIMI_VERO_MUUPOTULO = 0; 
%LET KYNNYS_VERO_MUUPOTULO = 500;

* Nettopalkka (e/kk), jos halutaan laskea käänteisfunktiolla bruttotulot;
%LET MINIMI_VERO_NETTOPALKKA = 0;
%LET MAKSIMI_VERO_NETTOPALKKA = 0;
%LET KYNNYS_VERO_NETTOPALKKA = 1000;

* Tuloaskel, jolla tuloa korotetaan 
  marginaaliveroastetta laskettaessa (e/v);
%LET MINIMI_VERO_ASKEL = 1;
%LET MAKSIMI_VERO_ASKEL = 1; 
%LET KYNNYS_VERO_ASKEL = 1; 

* Vakituinen asunto varallisuuden osana (1 = tosi, 0 = epätosi);
%LET MINIMI_VERO_VAKASU = 1;
%LET MAKSIMI_VERO_VAKASU = 1;

* Nettovarallisuus (e);
%LET MINIMI_VERO_NETTOVARALL = 300000;
%LET MAKSIMI_VERO_NETTOVARALL = 300000;
%LET KYNNYS_VERO_NETTOVARALL = 50000; */

/******************************************************/

* Tulonhankkimiskulut (e/v);
%LET MINIMI_VERO_TULONHANKKULUT = 0;
%LET MAKSIMI_VERO_TULONHANKKULUT = 0;
%LET KYNNYS_VERO_TULONHANKKULUT = 100;

* Ay-jäsenmaksut (e/v);
%LET MINIMI_VERO_AYMAKSUT = 0;
%LET MAKSIMI_VERO_AYMAKSUT = 0; 
%LET KYNNYS_VERO_AYMAKSUT = 100;

* Työmatkakulut (e/v);
%LET MINIMI_VERO_TYOMATKAKULUT = 0;
%LET MAKSIMI_VERO_TYOMATKAKULUT = 0; 
%LET KYNNYS_VERO_TYOMATKAKULUT = 100;

* Työasuntovähennykseen oikeuttavat kuukaudet (1-12);
%LET MINIMI_VERO_KUUKAUDET = 0;
%LET MAKSIMI_VERO_KUUKAUDET = 0;
%LET KYNNYS_VERO_KUUKAUDET = 1;

* Työasuntovähennykseen oikeuttava vuokra (e/kk); 
%LET MINIMI_VERO_VUOKRA = 0;
%LET MAKSIMI_VERO_VUOKRA = 0; 
%LET KYNNYS_VERO_VUOKRA = 500;

* Elatusmaksut (e/v);
%LET MINIMI_VERO_ELMAKSUT = 0;
%LET MAKSIMI_VERO_ELMAKSUT = 0;
%LET KYNNYS_VERO_ELMAKSUT = 500;

* Pääomatulon hankkimisesta aiheuttavat menot (e/v);
%LET MINIMI_VERO_POVAHENN = 0;
%LET MAKSIMI_VERO_POVAHENN = 0;
%LET KYNNYS_VERO_POVAHENN = 500;

* Asunto- ja opintolainan korot (e/v);
%LET MINIMI_VERO_ASKOROT = 0;
%LET MAKSIMI_VERO_ASKOROT = 0;
%LET KYNNYS_VERO_ASKOROT = 100;

* Ensiasuntoon kohdistuvan luoton korot (e/v);
%LET MINIMI_VERO_ENSASKOROT = 0;
%LET MAKSIMI_VERO_ENSASKOROT = 0; 
%LET KYNNYS_VERO_ENSASKOROT = 100;

* Kulutusluoton korot (e/v);
%LET MINIMI_VERO_KULKOROT = 0;
%LET MAKSIMI_VERO_KULKOROT = 0;
%LET KYNNYS_VERO_KULKOROT = 100; 

* Pääomatuloista vähennettäva vap.eht. eläkevakuutusmaksu (2005-) (e/v);
%LET MINIMI_VERO_ELVAKMAKSU = 0;
%LET MAKSIMI_VERO_ELVAKMAKSU = 0; 
%LET KYNNYS_VERO_ELVAKMAKSU = 100;

* Sairauskulut (e/v);
%LET MINIMI_VERO_SAIRKULUT = 0;
%LET MAKSIMI_VERO_SAIRKULUT = 0; 
%LET KYNNYS_VERO_SAIRKULUT = 500;

* Kotitalousvähennykseen oikeuttavat menot (e/v);
%LET MINIMI_VERO_KOTITMENO = 0;
%LET MAKSIMI_VERO_KOTITMENO = 0;
%LET KYNNYS_VERO_KOTITMENO = 250;

* Muita vähennyksiä tulosta valtionverotuksessa (e/v); 
%LET MINIMI_VERO_MUUVAHVALT = 0;
%LET MAKSIMI_VERO_MUUVAHVALT = 0;
%LET KYNNYS_VERO_MUUVAHVALT = 100;

* Muita vähennyksiä tulosta kunnallisverotuksessa (e/v);  
%LET MINIMI_VERO_MUUVAHKUNN = 0;
%LET MAKSIMI_VERO_MUUVAHKUNN = 0; 
%LET KYNNYS_VERO_MUUVAHKUNN = 100;

/******************************************************/

* Onko puolisoa (0 = ei puolisoa, 1 = on puoliso);
%LET MINIMI_VERO_PUOLISO = 0; 
%LET MAKSIMI_VERO_PUOLISO = 0;

* 53 vuotta täyttänyt (1 = tosi, 0 = epätosi);
%LET MINIMI_VERO_V53 = 0; 
%LET MAKSIMI_VERO_V53 = 0;
 
* Huollettavina olevien alaikäisten lasten lukumäärä;
%LET MINIMI_VERO_LAPSIA = 0; 
%LET MAKSIMI_VERO_LAPSIA = 0;

* Elatusvellvollisten lasten lukumäärä; 
%LET MINIMI_VERO_EVLAPSIA = 0; 
%LET MAKSIMI_VERO_EVLAPSIA = 0;

* Onko opiskelija (1 = tosi, 0 = epätosi);
%LET MINIMI_VERO_OPISK = 0; 
%LET MAKSIMI_VERO_OPISK = 0;

* Onko yrittäjä (1 = tosi, 0 = epätosi);
%LET MINIMI_VERO_YRIT = 0; 
%LET MAKSIMI_VERO_YRIT = 0;

* Vamman haitta-aste (1-100);
%LET MINIMI_VERO_INVPROS = 0; 
%LET MAKSIMI_VERO_INVPROS = 0;
%LET KYNNYS_VERO_INVPROS = 50;

* Työttömyyskuukaudet (1-12);
%LET MINIMI_VERO_TYOTKUUK = 0; 
%LET MAKSIMI_VERO_TYOTKUUK = 0;

* Puolison alijäämähyvitys (e/v);
%LET MINIMI_VERO_PUOLALIJ = 0; 
%LET MAKSIMI_VERO_PUOLALIJ = 0;
%LET KYNNYS_VERO_PUOLALIJ = 200;

* Kunnallinen veroprosentti (jos ei automaattisesti keskiarvo);
%LET MINIMI_VERO_KUNNPROS = 18.5; 
%LET MAKSIMI_VERO_KUNNPROS = 18.5;

* Kirkollinen veroprosentti (jos ei automaattisesti keskiarvo);
%LET MINIMI_VERO_KIRKPROS = 1.00; 
%LET MAKSIMI_VERO_KIRKPROS = 1.00;

* Käytetäänkö keskimääräistä kunnallis-, ja kirkollisveroprosenttia (1 = tosi, 0 = epätosi);
%LET MINIMI_VERO_KESKIM = 1; 
%LET MAKSIMI_VERO_KESKIM = 1;

* Kuuluuko kirkkoon (1 = tosi, 0 = epätosi);
%LET MINIMI_VERO_KIRKOSSA = 1; 
%LET MAKSIMI_VERO_KIRKOSSA = 1;

/******************************************************/

* Vaihtoehtoinen alempi osuus (1 = tosi, 0 = epätosi);
%LET MINIMI_VERO_VAIHT = 1;
%LET MAKSIMI_VERO_VAIHT = 1;

* Jaettava yritystulo (e/v);
%LET MINIMI_VERO_YTULO = 0;
%LET MAKSIMI_VERO_YTULO = 0;
%LET KYNNYS_VERO_YTULO = 5000;

* Yritysvarallisuus/Osakkeiden arvo (e);
%LET MINIMI_VERO_YRITVARALL = 0;
%LET MAKSIMI_VERO_YRITVARALL = 0;
%LET KYNNYS_VERO_YRITVARALL = 50000;

* Yrityksessä maksetut palkat;
%LET MINIMI_VERO_YPALKKA = 0;
%LET MAKSIMI_VERO_YPALKKA = 0;
%LET KYNNYS_VERO_YPALKKA = 2000;

* Osinkotulo (e/v);
%LET MINIMI_VERO_OTULO = 0;
%LET MAKSIMI_VERO_OTULO = 0;
%LET KYNNYS_VERO_OTULO = 5000;

* Onko julk.osinko osuuspääoman korkoa? (1 = tosi, 0 = epätosi);
%LET MINIMI_VERO_OSPKORKO = 0;
%LET MAKSIMI_VERO_OSPKORKO = 0;

* Osinko julk. noteeratusta yhtiöstä (e/v);
%LET MINIMI_VERO_JULKOSINKO = 0;
%LET MAKSIMI_VERO_JULKOSINKO = 0;
%LET KYNNYS_VERO_JULKOSINKO = 5000;

* Muu osinko (e/v);
%LET MINIMI_VERO_EIJULKOSINKO = 0;
%LET MAKSIMI_VERO_EIJULKOSINKO = 0;
%LET KYNNYS_VERO_EIJULKOSINKO = 5000;

* Muiden osakkeiden matemaattinen arvo (e);
%LET MINIMI_VERO_OSAKKARVO = 0;
%LET MAKSIMI_VERO_OSAKKARVO = 0;
%LET KYNNYS_VERO_OSAKKARVO = 10000;

/******************************************************/

/* 3.2 Pienituloisemman puolison fiktiivinen data */

* Palkkatulo (e/v);
%LET MINIMI_VERO_PPTULO = 30000;
%LET MAKSIMI_VERO_PPTULO = 30000; 
%LET KYNNYS_VERO_PPTULO = 5000;

* Muu työtulo kuin palkkatulo (e/v);
%LET MINIMI_VERO_PMTULO = 0;
%LET MAKSIMI_VERO_PMTULO = 0; 
%LET KYNNYS_VERO_PMTULO = 100;

* Päivärahatulo (e/v);
%LET MINIMI_VERO_PPRAHATULO = 0;
%LET MAKSIMI_VERO_PPRAHATULO = 0;
%LET KYNNYS_VERO_PPRAHATULO = 1000;

* Eläketulo (e/v);
%LET MINIMI_VERO_PETULO = 0;
%LET MAKSIMI_VERO_PETULO = 0;
%LET KYNNYS_VERO_PETULO = 1000;

* Opintoraha (e/v);
%LET MINIMI_VERO_POPRAHA = 0;
%LET MAKSIMI_VERO_POPRAHA = 0;
%LET KYNNYS_VERO_POPRAHA = 100;

* Osinkotulo ansiotulona (e/v);
%LET MINIMI_VERO_POSANSTULO = 0;
%LET MAKSIMI_VERO_POSANSTULO = 0;  
%LET KYNNYS_VERO_POSANSTULO = 500;

* Muu ansiotulo (e/v);
%LET MINIMI_VERO_PMUUANSTULO = 0;
%LET MAKSIMI_VERO_PMUUANSTULO = 0;
%LET KYNNYS_VERO_PMUUANSTULO = 500; 

* Osinkotulo pääomatulona (e/v);
%LET MINIMI_VERO_POSINKOTULO = 0;
%LET MAKSIMI_VERO_POSINKOTULO = 0;  
%LET KYNNYS_VERO_POSINKOTULO = 500;

* Vuokratulot vakituisesta asunnosta (e/v);
%LET MINIMI_VERO_PVUOKRATULO = 0;
%LET MAKSIMI_VERO_PVUOKRATULO = 0;
%LET KYNNYS_VERO_PVUOKRATULO = 500;

* Veronalaiset korkotulot (e/v);
%LET MINIMI_VERO_PKORKOTULO = 0;
%LET MAKSIMI_VERO_PKORKOTULO = 0;
%LET KYNNYS_VERO_PKORKOTULO = 500; 

* Muu pääomatulo (e/v);
%LET MINIMI_VERO_PMUUPOTULO = 0;
%LET MAKSIMI_VERO_PMUUPOTULO = 0; 
%LET KYNNYS_VERO_PMUUPOTULO = 500;

* Vakituinen asunto varallisuuden osana (1 = tosi, 0 = epätosi);
%LET MINIMI_VERO_PVAKASU = 0;
%LET MAKSIMI_VERO_PVAKASU = 0;

* Nettovarallisuus (e);
%LET MINIMI_VERO_PNETTOVARALL = 0;
%LET MAKSIMI_VERO_PNETTOVARALL = 0;
%LET KYNNYS_VERO_PNETTOVARALL = 50000;

/******************************************************/

* Tulonhankkimiskulut (e/v);
%LET MINIMI_VERO_PTULONHANKKULUT = 0;
%LET MAKSIMI_VERO_PTULONHANKKULUT = 0;
%LET KYNNYS_VERO_PTULONHANKKULUT = 100;

* Ay-jäsenmaksut (e/v);
%LET MINIMI_VERO_PAYMAKSUT = 0;
%LET MAKSIMI_VERO_PAYMAKSUT = 0; 
%LET KYNNYS_VERO_PAYMAKSUT = 100;

* Työmatkakulut (e/v);
%LET MINIMI_VERO_PTYOMATKAKULUT = 0;
%LET MAKSIMI_VERO_PTYOMATKAKULUT = 0; 
%LET KYNNYS_VERO_PTYOMATKAKULUT = 100;

* Työasuntovähennykseen oikeuttavat kuukaudet (1-12);
%LET MINIMI_VERO_PKUUKAUDET = 0;
%LET MAKSIMI_VERO_PKUUKAUDET = 0;
%LET KYNNYS_VERO_PKUUKAUDET = 1;

* Työasuntovähennykseen oikeuttava vuokra (e/kk); 
%LET MINIMI_VERO_PVUOKRA = 0;
%LET MAKSIMI_VERO_PVUOKRA = 0; 
%LET KYNNYS_VERO_PVUOKRA = 500;

* Elatusmaksut (e/v);
%LET MINIMI_VERO_PELMAKSUT = 0;
%LET MAKSIMI_VERO_PELMAKSUT = 0;
%LET KYNNYS_VERO_PELMAKSUT = 500;

* Pääomatulon hankkimisesta aiheuttavat menot (e/v);
%LET MINIMI_VERO_PPOVAHENN = 0;
%LET MAKSIMI_VERO_PPOVAHENN = 0;
%LET KYNNYS_VERO_PPOVAHENN = 500;

* Asunto- ja opintolainan korot (e/v);
%LET MINIMI_VERO_PASKOROT = 0;
%LET MAKSIMI_VERO_PASKOROT = 0;
%LET KYNNYS_VERO_PASKOROT = 100;

* Ensiasuntoon kohdistuvan luoton korot (e/v);
%LET MINIMI_VERO_PENSASKOROT = 0;
%LET MAKSIMI_VERO_PENSASKOROT = 0; 
%LET KYNNYS_VERO_PENSASKOROT = 100;

* Kulutusluoton korot (e/v);
%LET MINIMI_VERO_PKULKOROT = 0;
%LET MAKSIMI_VERO_PKULKOROT = 0;
%LET KYNNYS_VERO_PKULKOROT = 100; 

* Pääomatuloista vähennettäva vap.eht. eläkevakuutusmaksu (2005-) (e/v);
%LET MINIMI_VERO_PELVAKMAKSU = 0;
%LET MAKSIMI_VERO_PELVAKMAKSU = 0; 
%LET KYNNYS_VERO_PELVAKMAKSU = 100;

* Kotitalousvähennykseen oikeuttavat menot (e/v);
%LET MINIMI_VERO_PKOTITMENO = 0;
%LET MAKSIMI_VERO_PKOTITMENO = 0;
%LET KYNNYS_VERO_PKOTITMENO = 250;

* Muita vähennyksiä tulosta valtionverotuksessa (e/v); 
%LET MINIMI_VERO_PMUUVAHVALT = 0;
%LET MAKSIMI_VERO_PMUUVAHVALT = 0;
%LET KYNNYS_VERO_PMUUVAHVALT = 100;

* Muita vähennyksiä tulosta kunnallisverotuksessa (e/v);  
%LET MINIMI_VERO_PMUUVAHKUNN = 0;
%LET MAKSIMI_VERO_PMUUVAHKUNN = 0; 
%LET KYNNYS_VERO_PMUUVAHKUNN = 100;

/******************************************************/

* 53 vuotta täyttänyt (1 = tosi, 0 = epätosi);
%LET MINIMI_VERO_PV53 = 0; 
%LET MAKSIMI_VERO_PV53 = 0;
 
* Elatusvellvollisten lasten lukumäärä; 
%LET MINIMI_VERO_PEVLAPSIA = 0; 
%LET MAKSIMI_VERO_PEVLAPSIA = 0;

* Onko opiskelija (1 = tosi, 0 = epätosi);
%LET MINIMI_VERO_POPISK = 0; 
%LET MAKSIMI_VERO_POPISK = 0;

* Onko yrittäjä (1 = tosi, 0 = epätosi);
%LET MINIMI_VERO_PYRIT = 0; 
%LET MAKSIMI_VERO_PYRIT = 0;

* Vamman haitta-aste (1-100);
%LET MINIMI_VERO_PINVPROS = 0; 
%LET MAKSIMI_VERO_PINVPROS = 0;
%LET KYNNYS_VERO_PINVPROS = 50;

* Työttömyyskuukaudet (1-12);
%LET MINIMI_VERO_PTYOTKUUK = 0; 
%LET MAKSIMI_VERO_PTYOTKUUK = 0;

* Puolison alijäämähyvitys (e/v);
%LET MINIMI_VERO_PPUOLALIJ = 0; 
%LET MAKSIMI_VERO_PPUOLALIJ = 0;
%LET KYNNYS_VERO_PPUOLALIJ = 200;

* Kunnallinen veroprosentti (jos ei automaattisesti keskiarvo);
%LET MINIMI_VERO_PKUNNPROS = 18.5; 
%LET MAKSIMI_VERO_PKUNNPROS = 18.5;

* Kirkollinen veroprosentti (jos ei automaattisesti keskiarvo);
%LET MINIMI_VERO_PKIRKPROS = 1.00; 
%LET MAKSIMI_VERO_PKIRKPROS = 1.00;

* Käytetäänkö keskimääräistä kunnallis-, ja kirkollisveroprosenttia (1 = tosi, 0 = epätosi);
%LET MINIMI_VERO_PKESKIM = 1; 
%LET MAKSIMI_VERO_PKESKIM = 1;

* Kuuluuko kirkkoon (1 = tosi, 0 = epätosi);
%LET MINIMI_VERO_PKIRKOSSA = 1; 
%LET MAKSIMI_VERO_PKIRKOSSA = 1;

/******************************************************/

%END;


/* 4. Fiktiivisen aineiston luominen ja simulointi */

/* 4.1 Generoidaan data makromuuttujien arvojen mukaisesti */ 

DATA OUTPUT.&TULOSNIMI_VE;

DO VERO_VUOSI = &MINIMI_VERO_VUOSI TO &MAKSIMI_VERO_VUOSI;
DO VERO_PTULO = &MINIMI_VERO_PTULO TO &MAKSIMI_VERO_PTULO BY &KYNNYS_VERO_PTULO; 
DO VERO_MTULO = &MINIMI_VERO_MTULO TO &MAKSIMI_VERO_MTULO BY &KYNNYS_VERO_MTULO;
DO VERO_PRAHATULO = &MINIMI_VERO_PRAHATULO TO &MAKSIMI_VERO_PRAHATULO BY &KYNNYS_VERO_PRAHATULO; 
DO VERO_ETULO = &MINIMI_VERO_ETULO TO &MAKSIMI_VERO_ETULO BY &KYNNYS_VERO_ETULO;
DO VERO_OPRAHA = &MINIMI_VERO_OPRAHA TO &MAKSIMI_VERO_OPRAHA BY &KYNNYS_VERO_OPRAHA;
DO VERO_OSANSTULO = &MINIMI_VERO_OSANSTULO TO &MAKSIMI_VERO_OSANSTULO BY &KYNNYS_VERO_OSANSTULO;  
DO VERO_MUUANSTULO = &MINIMI_VERO_MUUANSTULO TO &MAKSIMI_VERO_MUUANSTULO BY &KYNNYS_VERO_MUUANSTULO;
DO VERO_OSINKOTULO = &MINIMI_VERO_OSINKOTULO TO &MAKSIMI_VERO_OSINKOTULO BY &KYNNYS_VERO_OSINKOTULO;   
DO VERO_VUOKRATULO = &MINIMI_VERO_VUOKRATULO TO &MAKSIMI_VERO_VUOKRATULO BY &KYNNYS_VERO_VUOKRATULO;
DO VERO_KORKOTULO = &MINIMI_VERO_KORKOTULO TO &MAKSIMI_VERO_KORKOTULO BY &KYNNYS_VERO_KORKOTULO;
DO VERO_MUUPOTULO = &MINIMI_VERO_MUUPOTULO TO &MAKSIMI_VERO_MUUPOTULO BY &KYNNYS_VERO_MUUPOTULO;
DO VERO_NETTOPALKKA = &MINIMI_VERO_NETTOPALKKA TO &MAKSIMI_VERO_NETTOPALKKA BY &KYNNYS_VERO_NETTOPALKKA;
DO VERO_ASKEL = &MINIMI_VERO_ASKEL TO &MAKSIMI_VERO_ASKEL BY &KYNNYS_VERO_ASKEL;
DO VERO_VAKASU = &MINIMI_VERO_VAKASU TO &MAKSIMI_VERO_VAKASU;
DO VERO_NETTOVARALL = &MINIMI_VERO_NETTOVARALL TO &MAKSIMI_VERO_NETTOVARALL BY &KYNNYS_VERO_NETTOVARALL;

DO VERO_TULONHANKKULUT = &MINIMI_VERO_TULONHANKKULUT TO &MAKSIMI_VERO_TULONHANKKULUT BY &KYNNYS_VERO_TULONHANKKULUT;
DO VERO_AYMAKSUT = &MINIMI_VERO_AYMAKSUT TO &MAKSIMI_VERO_AYMAKSUT BY &KYNNYS_VERO_AYMAKSUT; 
DO VERO_TYOMATKAKULUT = &MINIMI_VERO_TYOMATKAKULUT TO &MAKSIMI_VERO_TYOMATKAKULUT BY &KYNNYS_VERO_TYOMATKAKULUT; 
DO VERO_KUUKAUDET = &MINIMI_VERO_KUUKAUDET TO &MAKSIMI_VERO_KUUKAUDET BY &KYNNYS_VERO_KUUKAUDET;
DO VERO_VUOKRA = &MINIMI_VERO_VUOKRA TO &MAKSIMI_VERO_VUOKRA BY &KYNNYS_VERO_VUOKRA;
DO VERO_ELMAKSUT = &MINIMI_VERO_ELMAKSUT TO &MAKSIMI_VERO_ELMAKSUT BY &KYNNYS_VERO_ELMAKSUT;
DO VERO_POVAHENN = &MINIMI_VERO_POVAHENN TO &MAKSIMI_VERO_POVAHENN BY &KYNNYS_VERO_POVAHENN;
DO VERO_ASKOROT = &MINIMI_VERO_ASKOROT TO &MAKSIMI_VERO_ASKOROT BY &KYNNYS_VERO_ASKOROT;
DO VERO_ENSASKOROT = &MINIMI_VERO_ENSASKOROT TO &MAKSIMI_VERO_ENSASKOROT BY &KYNNYS_VERO_ENSASKOROT;
DO VERO_KULKOROT = &MINIMI_VERO_KULKOROT TO &MAKSIMI_VERO_KULKOROT BY &KYNNYS_VERO_KULKOROT;
DO VERO_ELVAKMAKSU = &MINIMI_VERO_ELVAKMAKSU TO &MAKSIMI_VERO_ELVAKMAKSU BY &KYNNYS_VERO_ELVAKMAKSU; 
DO VERO_SAIRKULUT = &MINIMI_VERO_SAIRKULUT TO &MAKSIMI_VERO_SAIRKULUT BY &KYNNYS_VERO_SAIRKULUT; 
DO VERO_KOTITMENO = &MINIMI_VERO_KOTITMENO TO &MAKSIMI_VERO_KOTITMENO BY &KYNNYS_VERO_KOTITMENO;
DO VERO_MUUVAHVALT = &MINIMI_VERO_MUUVAHVALT TO &MAKSIMI_VERO_MUUVAHVALT BY &KYNNYS_VERO_MUUVAHVALT; 
DO VERO_MUUVAHKUNN = &MINIMI_VERO_MUUVAHKUNN TO &MAKSIMI_VERO_MUUVAHKUNN BY &KYNNYS_VERO_MUUVAHKUNN; 

DO VERO_PUOLISO = &MINIMI_VERO_PUOLISO TO &MAKSIMI_VERO_PUOLISO;
DO VERO_V53 = &MINIMI_VERO_V53 TO &MAKSIMI_VERO_V53;
DO VERO_LAPSIA = &MINIMI_VERO_LAPSIA TO &MAKSIMI_VERO_LAPSIA;
DO VERO_EVLAPSIA = &MINIMI_VERO_EVLAPSIA TO &MAKSIMI_VERO_EVLAPSIA;
DO VERO_OPISK = &MINIMI_VERO_OPISK TO &MAKSIMI_VERO_OPISK;
DO VERO_YRIT = &MINIMI_VERO_YRIT TO &MAKSIMI_VERO_YRIT;
DO VERO_INVPROS = &MINIMI_VERO_INVPROS TO &MAKSIMI_VERO_INVPROS BY &KYNNYS_VERO_INVPROS;
DO VERO_TYOTKUUK = &MINIMI_VERO_TYOTKUUK TO &MAKSIMI_VERO_TYOTKUUK;
DO VERO_PUOLALIJ = &MINIMI_VERO_PUOLALIJ TO &MAKSIMI_VERO_PUOLALIJ BY &KYNNYS_VERO_PUOLALIJ;
DO VERO_KUNNPROS = &MINIMI_VERO_KUNNPROS TO &MAKSIMI_VERO_KUNNPROS;
DO VERO_KIRKPROS = &MINIMI_VERO_KIRKPROS TO &MAKSIMI_VERO_KIRKPROS;
DO VERO_KESKIM = &MINIMI_VERO_KESKIM TO &MAKSIMI_VERO_KESKIM;
DO VERO_KIRKOSSA = &MINIMI_VERO_KIRKOSSA TO &MAKSIMI_VERO_KIRKOSSA;

DO VERO_VAIHT = &MINIMI_VERO_VAIHT TO &MAKSIMI_VERO_VAIHT;
DO VERO_YTULO = &MINIMI_VERO_YTULO TO &MAKSIMI_VERO_YTULO BY &KYNNYS_VERO_YTULO;
DO VERO_YRITVARALL = &MINIMI_VERO_YRITVARALL TO &MAKSIMI_VERO_YRITVARALL BY &KYNNYS_VERO_YRITVARALL;
DO VERO_YPALKKA = &MINIMI_VERO_YPALKKA TO &MAKSIMI_VERO_YPALKKA BY &KYNNYS_VERO_YPALKKA;
DO VERO_OTULO = &MINIMI_VERO_OTULO TO &MAKSIMI_VERO_OTULO BY &KYNNYS_VERO_OTULO;
DO VERO_OSPKORKO = &MINIMI_VERO_OSPKORKO TO &MAKSIMI_VERO_OSPKORKO;
DO VERO_JULKOSINKO = &MINIMI_VERO_JULKOSINKO TO &MAKSIMI_VERO_JULKOSINKO BY &KYNNYS_VERO_JULKOSINKO;
DO VERO_EIJULKOSINKO = &MINIMI_VERO_EIJULKOSINKO TO &MAKSIMI_VERO_EIJULKOSINKO BY &KYNNYS_VERO_EIJULKOSINKO;
DO VERO_OSAKKARVO = &MINIMI_VERO_OSAKKARVO TO &MAKSIMI_VERO_OSAKKARVO BY &KYNNYS_VERO_OSAKKARVO;

/*************** Puolison data (luodaan, jos VERO_PUOLISO = 1) **************************/

%IF &MINIMI_VERO_PUOLISO = 1 OR &MAKSIMI_VERO_PUOLISO = 1 %THEN %DO;

DO VERO_PPTULO = &MINIMI_VERO_PPTULO TO &MAKSIMI_VERO_PPTULO BY &KYNNYS_VERO_PPTULO; 
DO VERO_PMTULO = &MINIMI_VERO_PMTULO TO &MAKSIMI_VERO_PMTULO BY &KYNNYS_VERO_PMTULO;
DO VERO_PPRAHATULO = &MINIMI_VERO_PPRAHATULO TO &MAKSIMI_VERO_PPRAHATULO BY &KYNNYS_VERO_PPRAHATULO;  
DO VERO_PETULO = &MINIMI_VERO_PETULO TO &MAKSIMI_VERO_PETULO BY &KYNNYS_VERO_PETULO;
DO VERO_POPRAHA = &MINIMI_VERO_POPRAHA TO &MAKSIMI_VERO_POPRAHA BY &KYNNYS_VERO_POPRAHA;
DO VERO_POSANSTULO = &MINIMI_VERO_POSANSTULO TO &MAKSIMI_VERO_POSANSTULO BY &KYNNYS_VERO_POSANSTULO;  
DO VERO_PMUUANSTULO = &MINIMI_VERO_PMUUANSTULO TO &MAKSIMI_VERO_PMUUANSTULO BY &KYNNYS_VERO_PMUUANSTULO;
DO VERO_POSINKOTULO = &MINIMI_VERO_POSINKOTULO TO &MAKSIMI_VERO_POSINKOTULO BY &KYNNYS_VERO_POSINKOTULO;   
DO VERO_PVUOKRATULO = &MINIMI_VERO_PVUOKRATULO TO &MAKSIMI_VERO_PVUOKRATULO BY &KYNNYS_VERO_PVUOKRATULO;
DO VERO_PKORKOTULO = &MINIMI_VERO_PKORKOTULO TO &MAKSIMI_VERO_PKORKOTULO BY &KYNNYS_VERO_PKORKOTULO;
DO VERO_PMUUPOTULO = &MINIMI_VERO_PMUUPOTULO TO &MAKSIMI_VERO_PMUUPOTULO BY &KYNNYS_VERO_PMUUPOTULO;
DO VERO_PVAKASU = &MINIMI_VERO_PVAKASU TO &MAKSIMI_VERO_PVAKASU;
DO VERO_PNETTOVARALL = &MINIMI_VERO_PNETTOVARALL TO &MAKSIMI_VERO_PNETTOVARALL BY &KYNNYS_VERO_PNETTOVARALL;

DO VERO_PTULONHANKKULUT = &MINIMI_VERO_PTULONHANKKULUT TO &MAKSIMI_VERO_PTULONHANKKULUT BY &KYNNYS_VERO_PTULONHANKKULUT;
DO VERO_PAYMAKSUT = &MINIMI_VERO_PAYMAKSUT TO &MAKSIMI_VERO_PAYMAKSUT BY &KYNNYS_VERO_PAYMAKSUT; 
DO VERO_PTYOMATKAKULUT = &MINIMI_VERO_PTYOMATKAKULUT TO &MAKSIMI_VERO_PTYOMATKAKULUT BY &KYNNYS_VERO_PTYOMATKAKULUT; 
DO VERO_PKUUKAUDET = &MINIMI_VERO_PKUUKAUDET TO &MAKSIMI_VERO_PKUUKAUDET BY &KYNNYS_VERO_PKUUKAUDET;
DO VERO_PVUOKRA = &MINIMI_VERO_PVUOKRA TO &MAKSIMI_VERO_PVUOKRA BY &KYNNYS_VERO_PVUOKRA;
DO VERO_PELMAKSUT = &MINIMI_VERO_PELMAKSUT TO &MAKSIMI_VERO_PELMAKSUT BY &KYNNYS_VERO_PELMAKSUT;
DO VERO_PPOVAHENN = &MINIMI_VERO_PPOVAHENN TO &MAKSIMI_VERO_PPOVAHENN BY &KYNNYS_VERO_PPOVAHENN;
DO VERO_PASKOROT = &MINIMI_VERO_PASKOROT TO &MAKSIMI_VERO_PASKOROT BY &KYNNYS_VERO_PASKOROT;
DO VERO_PENSASKOROT = &MINIMI_VERO_PENSASKOROT TO &MAKSIMI_VERO_PENSASKOROT BY &KYNNYS_VERO_PENSASKOROT;
DO VERO_PKULKOROT = &MINIMI_VERO_PKULKOROT TO &MAKSIMI_VERO_PKULKOROT BY &KYNNYS_VERO_PKULKOROT;
DO VERO_PELVAKMAKSU = &MINIMI_VERO_PELVAKMAKSU TO &MAKSIMI_VERO_PELVAKMAKSU BY &KYNNYS_VERO_PELVAKMAKSU; 
DO VERO_PKOTITMENO = &MINIMI_VERO_PKOTITMENO TO &MAKSIMI_VERO_PKOTITMENO BY &KYNNYS_VERO_PKOTITMENO;
DO VERO_PMUUVAHVALT = &MINIMI_VERO_PMUUVAHVALT TO &MAKSIMI_VERO_PMUUVAHVALT BY &KYNNYS_VERO_PMUUVAHVALT; 
DO VERO_PMUUVAHKUNN = &MINIMI_VERO_PMUUVAHKUNN TO &MAKSIMI_VERO_PMUUVAHKUNN BY &KYNNYS_VERO_PMUUVAHKUNN; 

DO VERO_PV53 = &MINIMI_VERO_PV53 TO &MAKSIMI_VERO_PV53;
DO VERO_PEVLAPSIA = &MINIMI_VERO_PEVLAPSIA TO &MAKSIMI_VERO_PEVLAPSIA;
DO VERO_POPISK = &MINIMI_VERO_POPISK TO &MAKSIMI_VERO_POPISK;
DO VERO_PYRIT = &MINIMI_VERO_PYRIT TO &MAKSIMI_VERO_PYRIT;
DO VERO_PINVPROS = &MINIMI_VERO_PINVPROS TO &MAKSIMI_VERO_PINVPROS BY &KYNNYS_VERO_PINVPROS;
DO VERO_PTYOTKUUK = &MINIMI_VERO_PTYOTKUUK TO &MAKSIMI_VERO_PTYOTKUUK;
DO VERO_PPUOLALIJ = &MINIMI_VERO_PPUOLALIJ TO &MAKSIMI_VERO_PPUOLALIJ BY &KYNNYS_VERO_PPUOLALIJ;
DO VERO_PKIRKPROS = &MINIMI_VERO_PKIRKPROS TO &MAKSIMI_VERO_PKIRKPROS;
DO VERO_PKUNNPROS = &MINIMI_VERO_PKUNNPROS TO &MAKSIMI_VERO_PKUNNPROS;
DO VERO_PKESKIM = &MINIMI_VERO_PKESKIM TO &MAKSIMI_VERO_PKESKIM;
DO VERO_PKIRKOSSA = &MINIMI_VERO_PKIRKOSSA TO &MAKSIMI_VERO_PKIRKOSSA;

%END;

%IF &INF = 999 %THEN %DO;
%IndKerroin_ESIM(&AVUOSI, VERO_VUOSI);
%END;
%ELSE %DO; 
	INF = &INF;
%END;

OUTPUT;

END;END;END;END;END;END;END;END;END;END;END;END;END;END;
END;END;END;END;END;END;END;END;END;END;END;END;END;END;END;
END;END;END;END;END;END;END;END;END;END;END;END;END;END;
END;END;END;END;END;END;END;END;END;END;

%IF &MINIMI_VERO_PUOLISO = 1 OR &MAKSIMI_VERO_PUOLISO = 1 %THEN %DO;

	END;END;END;END;END;END;END;END;END;END;END;END;END;
	END;END;END;END;END;END;END;END;END;END;END;END;END;END;
	END;END;END;END;END;END;END;END;END;END;END;

%END;

RUN;

%IF &MINIMI_VERO_PUOLISO = 1 OR &MAKSIMI_VERO_PUOLISO = 1 %THEN %DO;

	DATA OUTPUT.&TULOSNIMI_VE; 
	SET OUTPUT.&TULOSNIMI_VE;

	ARRAY PUOLISO VERO_PPTULO--VERO_PKIRKOSSA;
		DO OVER PUOLISO;
			IF VERO_PUOLISO = 0 THEN PUOLISO = .;
		END;
	RUN;

%END;

%MEND Generoi_Muuttujat;

%Generoi_Muuttujat;


/* 4.2 Simuloidaan valitut muuttujat esimerkkiaineistolla */

%MACRO Vero_Simuloi_Esimerkki;

DATA OUTPUT.&TULOSNIMI_VE;
SET OUTPUT.&TULOSNIMI_VE;

/* 4.2.1 Lasketaan palkkaverotuksen tuloverot */

IF VERO_PTULO > 0 THEN DO;
	%TuloVerot_Simple&F(TULOVERO, VERO_VUOSI, INF, VERO_PTULO);

	/* Verojen osuus tuloista */
	VOSUUSPTULO = (TULOVERO / VERO_PTULO) * 100;

END;

/* 4.2.2 Lasketaan käänteisfunktiolla nettokuukausituloa vastaava bruttokuukausitulo */

IF VERO_NETTOPALKKA > 0 THEN DO;
	%Bruttotulo&F(BRUTTOTULO, VERO_VUOSI, INF, VERO_NETTOPALKKA);

	/* Verojen osuus tuloista */
	VOSUUSNKTULO = ((BRUTTOTULO - VERO_NETTOPALKKA) / BRUTTOTULO) * 100;

END;

/* 4.2.3 Lasketaan marginaaliveroaste */

IF VERO_PTULO > 0 THEN DO;
	%TuloVerot_SimpleMarg&F(MARGINAALIVERO, VERO_VUOSI, INF, VERO_PTULO, VERO_ASKEL);

	MARGINAALIVEROASTE = MARGINAALIVERO * 100;

	DROP MARGINAALIVERO;

END;

/* 4.2.4 Lasketaan eläketulonverot */

IF VERO_ETULO > 0 THEN DO;
	%TuloVerot_Simple_Elake&F(TULOVERO_ELAKE, VERO_VUOSI, INF, VERO_PUOLISO, VERO_ETULO);

	/* Verojen osuus tuloista */
	VOSUUSETULO = (TULOVERO_ELAKE / VERO_ETULO) * 100;

END;

/* 4.2.5 Lasketaan tuloverot kun tulot ovat työttömyysturvaa tai muuta vastaavaa sosiaalietuutta */ 

IF VERO_PRAHATULO > 0 THEN DO;
	%TuloVerot_Simple_PRaha&F(TULOVERO_PRAHA, VERO_VUOSI, INF, VERO_PRAHATULO);

	/* Verojen osuus tuloista */
	VOSUUSPRAHATULO = (TULOVERO_PRAHA / VERO_PRAHATULO) * 100;

END;

/* 4.2.6 Veromalli */

* Johdettuja tulokäsitteitä ja vähennyksiä ym. (e/v);

* Kokonaistulot;

KOKONTULO = (VERO_PTULO + VERO_PRAHATULO + VERO_MTULO + VERO_ETULO + VERO_OPRAHA + VERO_OSANSTULO + VERO_MUUANSTULO + VERO_OSINKOTULO + VERO_VUOKRATULO + VERO_KORKOTULO + VERO_MUUPOTULO);

* Ansiotulot (ilman yhtiöveron hyvitystä);

ANSIOTULO = (VERO_PTULO + VERO_PRAHATULO + VERO_MTULO + VERO_ETULO + VERO_OPRAHA + VERO_OSANSTULO + VERO_MUUANSTULO);

*Pääomatulot (ilman yhtiöveron hyvitystä);

POTULO = (VERO_OSINKOTULO + VERO_VUOKRATULO + VERO_KORKOTULO + VERO_MUUPOTULO);

PUHDPOTULO = POTULO - VERO_POVAHENN;

* Puhdas ansiotulo;

%TulonHankKulut&F(TULHANKSUMS, VERO_VUOSI, INF, VERO_MTULO, VERO_PTULO, VERO_TULONHANKKULUT, VERO_AYMAKSUT, VERO_TYOMATKAKULUT, VERO_KUUKAUDET);

%AsuntoVahennys&F(ASUNTOVAH, VERO_VUOSI, INF, VERO_KUUKAUDET, VERO_VUOKRA);

PUHDANSTULO = ANSIOTULO - (TULHANKSUMS + ASUNTOVAH);

IF PUHDANSTULO < 0 THEN PUHDANSTULO = 0;

* Vähennykset vain valtionverotuksessa;

%ValtElTulVah&F(ELVAHV, VERO_VUOSI, INF, VERO_ETULO, PUHDANSTULO, KOKONTULO);

%ValtTyoTuloVah&F(VALTTVAH, VERO_VUOSI, INF, ANSIOTULO, VERO_PTULO);

* Vähennykset vain kunnallisverotuksessa;

MUUANS2 = MAX(ANSIOTULO - VERO_ETULO,0);

%KunnAnsVah&F(KUNNANS, VERO_VUOSI, INF, PUHDANSTULO, MUUANS2, (VERO_PTULO + VERO_MTULO), VERO_PTULO, KOKONTULO);

%KunnElTulVah&F(ELVELVAHK, VERO_VUOSI, INF, VERO_PUOLISO, 0, VERO_ETULO, PUHDANSTULO, KOKONTULO);

%KunnOpRahVah&F(OPRAHVAHK, VERO_VUOSI, INF, VERO_OPISK, VERO_OPRAHA, ANSIOTULO, PUHDANSTULO);

%PalkVakMaksu&F(PALKVAKMAKSU, VERO_VUOSI, VERO_V53, VERO_PTULO);

%SvPrahaMaksu&F(SPM, VERO_VUOSI, VERO_PTULO);

%SvPRahaMaksuY&F(SPMY, VERO_VUOSI, 1, (VERO_OSINKOTULO));

SPMAKSU = SPM + SPMY;

* Verotettava tulo kunnallisverotuksessa ennen perusvähennystä;
	
%YhtHyv&F(YHTHYVPO, VERO_VUOSI, VERO_OSINKOTULO);

IF VERO_VUOSI < 1993 THEN PA = (KOKONTULO + YHTHYVPO - TULHANKSUMS - VERO_POVAHENN);
ELSE PA = PUHDANSTULO;

KUNNVEROTULO = MAX(PA - PALKVAKMAKSU - SPMAKSU - KUNNANS - ELVELVAHK - OPRAHVAHK - VERO_MUUVAHKUNN,0);

IF KUNNVEROTULO < 0 THEN KUNNVEROTULO = 0;

%KunnPerVah&F(PERVAH, VERO_VUOSI, INF, KUNNVEROTULO);

*Verotettava tulo kunnallisverotuksessa;

KUNNVERTULOSP = MAX(KUNNVEROTULO - PERVAH,0);

* Vähennyksiä veroista;

%ValtVerAnsVah&F(VALTANSVAH, VERO_VUOSI, INF,  (VERO_PTULO + VERO_MTULO + VERO_OSANSTULO), PUHDANSTULO);

%ValtVerInvVah&F(INVVAH, VERO_VUOSI, INF, VERO_INVPROS, VERO_ETULO);

%ValtVerElVelvVah&F(VELVVAHV, VERO_VUOSI, INF, VERO_EVLAPSIA, VERO_ELMAKSUT);

%AlijHyv&F(ALIJHYV, VERO_VUOSI, INF, VERO_PUOLISO, VERO_LAPSIA, (POTULO + YHTHYVPO), VERO_POVAHENN, VERO_ASKOROT, VERO_ENSASKOROT, VERO_KULKOROT, VERO_PUOLALIJ);

%AlijHyvErit&F(ALIJHYVERIT, VERO_VUOSI, INF, (POTULO + YHTHYVPO), VERO_POVAHENN, VERO_ASKOROT, VERO_ENSASKOROT, VERO_ELVAKMAKSU);

%KotiTalVah&F(KOTIVAH, VERO_VUOSI, INF, VERO_KOTITMENO);

* Yhtiöveron hyvitys;

IF VERO_VUOSI > 1992 THEN DO;

	%YhtHyv&F(YHTHYVANS, VERO_VUOSI, VERO_OSANSTULO);

END;

ELSE YHTHYVANS = 0;

%YhtHyv&F(YHTHYVPO, VERO_VUOSI, VERO_OSINKOTULO);

YHTHYVYHT = YHTHYVANS + YHTHYVPO;

IF VERO_VUOSI < 1993 THEN DO;
	TEMPA = KOKONTULO; 
   	TEMPB = YHTHYVPO;
END;

ELSE DO;
	TEMPA = ANSIOTULO;
	TEMPB = 0;
END;
 
VALTVEROTULO = MAX(TEMPA + TEMPB + YHTHYVANS - TULHANKSUMS - PALKVAKMAKSU - SPMAKSU - ELVAHV - VALTTVAH - VERO_MUUVAHVALT,0); 

IF VALTVEROTULO < 0 THEN VALTVEROTULO = 0;

IF VERO_VUOSI < 1995 THEN TEMPC = VERO_KULKOROT;
ELSE TEMPC = 0;

VEROPOTULO = MAX(POTULO + YHTHYVPO - VERO_ASKOROT, VERO_ENSASKOROT - VERO_POVAHENN - TEMPC, 0); 

IF VERO_VUOSI < 1993 THEN YHTVALTVEROTULO = VALTVEROTULO;
ELSE YHTVALTVEROTULO = VALTVEROTULO + VEROPOTULO;

* Tuloverot ennen ansiotulovähennystä;

%ValtTuloVero&F(VALTTULOVERO, VERO_VUOSI, INF, VALTVEROTULO);

%ElakeLisaVero&F(ELAKELISAVERO, VERO_VUOSI, INF, VERO_ETULO, ELVAHV);

VALTTULOVERO = SUM(VALTTULOVERO, ELAKELISAVERO);

%KunnVero&F(KUNNVERO, VERO_VUOSI, VERO_KESKIM, VERO_KUNNPROS, KUNNVERTULOSP);

%SairVakMaksu&F(SVMAKSU, VERO_VUOSI, INF, KUNNVERTULOSP, VERO_ETULO, (VERO_PTULO + VERO_MTULO));

%KansElVakMaksu&F(KEVMAKSU, VERO_VUOSI, KUNNVERTULOSP, VERO_ETULO);

IF VERO_KIRKOSSA = 1 THEN DO;
	%KirkVero&F(KIRKVEROS, VERO_VUOSI, VERO_KESKIM, VERO_KIRKPROS, KUNNVERTULOSP);
END;
ELSE KIRKVEROS = 0;

%POTulonVeroErit&F(POTULOVERO, VERO_VUOSI, INF, VERO_OSINKOTULO, (VERO_VUOKRATULO + VERO_KORKOTULO + VERO_MUUPOTULO), (VERO_POVAHENN + VERO_ASKOROT + VERO_ENSASKOROT), VERO_KULKOROT, VERO_ELVAKMAKSU);

* Tuloverot valtionverotuksen ansio/työtulovähennyksen jälkeen (jaetaan eri verolajeille, jos vuosi > 2008);

IF VERO_VUOSI > 2008 THEN DO;

	%VahennJako&F(VALTTULOANSVERO, VERO_VUOSI, VALTANSVAH, 1, VALTTULOVERO, KUNNVERO, SVMAKSU, KEVMAKSU, KIRKVEROS, 0);

	%VahennJako&F(KUNNALLISVERO, VERO_VUOSI, VALTANSVAH, 2, VALTTULOVERO, KUNNVERO, SVMAKSU, KEVMAKSU, KIRKVEROS, 0);

	%VahennJako&F(SAIRAUSVAKUUTUSMAKSU, VERO_VUOSI, VALTANSVAH, 3, VALTTULOVERO, KUNNVERO, SVMAKSU, KEVMAKSU, KIRKVEROS, 0);

	%VahennJako&F(KELAVAKUUTUSMAKSU, VERO_VUOSI, VALTANSVAH, 4, VALTTULOVERO, KUNNVERO, SVMAKSU, KEVMAKSU, KIRKVEROS, 0);

	%VahennJako&F(KIRKOLLISVERO, VERO_VUOSI, VALTANSVAH, 5, VALTTULOVERO, KUNNVERO, SVMAKSU, KEVMAKSU, KIRKVEROS, 0);
	
END;

ELSE DO;

	VALTTULOANSVERO = MAX(VALTTULOVERO - VALTANSVAH, 0);

	KUNNALLISVERO = KUNNVERO;

	SAIRAUSVAKUUTUSMAKSU = SVMAKSU;

	KELAVAKUUTUSMAKSU = KEVMAKSU;

	KIRKOLLISVERO = KIRKVEROS;

END;

* Valtion tulovero invalidi- ja ansiotulovähennyksen jälkeen;

VALTTULOINV = MAX(VALTTULOANSVERO - INVVAH - VELVVAHV,0);

* Tuloverot kotitalousvähennyksen jälkeen;

%VahennJako&F(VALTTULOANSVERO2, VERO_VUOSI, KOTIVAH, 1, VALTTULOINV, KUNNALLISVERO, SAIRAUSVAKUUTUSMAKSU, KELAVAKUUTUSMAKSU, KIRKOLLISVERO, POTULOVERO);

%VahennJako&F(KUNNALLISVERO2, VERO_VUOSI, KOTIVAH, 2, VALTTULOINV, KUNNALLISVERO, SAIRAUSVAKUUTUSMAKSU, KELAVAKUUTUSMAKSU, KIRKOLLISVERO, POTULOVERO);

%VahennJako&F(SAIRAUSVAKUUTUSMAKSU2, VERO_VUOSI, KOTIVAH, 3, VALTTULOINV, KUNNALLISVERO, SAIRAUSVAKUUTUSMAKSU, KELAVAKUUTUSMAKSU, KIRKOLLISVERO, POTULOVERO);

%VahennJako&F(KELAVAKUUTUSMAKSU2, VERO_VUOSI, KOTIVAH, 4, VALTTULOINV, KUNNALLISVERO, SAIRAUSVAKUUTUSMAKSU, KELAVAKUUTUSMAKSU, KIRKOLLISVERO, POTULOVERO);

%VahennJako&F(KIRKOLLISVERO2, VERO_VUOSI, KOTIVAH, 5, VALTTULOINV, KUNNALLISVERO, SAIRAUSVAKUUTUSMAKSU, KELAVAKUUTUSMAKSU, KIRKOLLISVERO, POTULOVERO);

%VahennJako&F(PAAOMAVERO2, VERO_VUOSI, KOTIVAH, 6, VALTTULOINV, KUNNALLISVERO, SAIRAUSVAKUUTUSMAKSU, KELAVAKUUTUSMAKSU, KIRKOLLISVERO, POTULOVERO);

* Tuloverot alijäämähyvityksen jälkeen;

%AlijHyvJako&F(VALTTULOANSVERO3, VERO_VUOSI, 1, ALIJHYV, VALTTULOANSVERO2, KUNNALLISVERO2, SAIRAUSVAKUUTUSMAKSU2, KELAVAKUUTUSMAKSU2, KIRKOLLISVERO2);

%AlijHyvJako&F(KUNNALLISVERO3, VERO_VUOSI, 2, ALIJHYV, VALTTULOANSVERO2, KUNNALLISVERO2, SAIRAUSVAKUUTUSMAKSU2, KELAVAKUUTUSMAKSU2, KIRKOLLISVERO2);

%AlijHyvJako&F(SAIRAUSVAKUUTUSMAKSU3, VERO_VUOSI, 3, ALIJHYV, VALTTULOANSVERO2, KUNNALLISVERO2, SAIRAUSVAKUUTUSMAKSU2, KELAVAKUUTUSMAKSU2, KIRKOLLISVERO2);

%AlijHyvJako&F(KELAVAKUUTUSMAKSU3, VERO_VUOSI, 4, ALIJHYV, VALTTULOANSVERO2, KUNNALLISVERO2, SAIRAUSVAKUUTUSMAKSU2, KELAVAKUUTUSMAKSU2, KIRKOLLISVERO2);

%AlijHyvJako&F(KIRKOLLISVERO3, VERO_VUOSI, 5, ALIJHYV, VALTTULOANSVERO2, KUNNALLISVERO2, SAIRAUSVAKUUTUSMAKSU2, KELAVAKUUTUSMAKSU2, KIRKOLLISVERO2);

* Tuloverot erityisen alijäämähyvityksen jälkeen; 

%VahennJako&F(VALTTULOANSVERO4, VERO_VUOSI, ALIJHYVERIT, 1, VALTTULOANSVERO3, KUNNALLISVERO3, SAIRAUSVAKUUTUSMAKSU3, KELAVAKUUTUSMAKSU3, KIRKOLLISVERO3, 0);

%VahennJako&F(KUNNALLISVERO4, VERO_VUOSI, ALIJHYVERIT, 2, VALTTULOANSVERO3, KUNNALLISVERO3, SAIRAUSVAKUUTUSMAKSU3, KELAVAKUUTUSMAKSU3, KIRKOLLISVERO3, 0);

%VahennJako&F(SAIRAUSVAKUUTUSMAKSU4, VERO_VUOSI, ALIJHYVERIT, 3, VALTTULOANSVERO3, KUNNALLISVERO3, SAIRAUSVAKUUTUSMAKSU3, KELAVAKUUTUSMAKSU3, KIRKOLLISVERO3, 0);

%VahennJako&F(KELAVAKUUTUSMAKSU4, VERO_VUOSI, ALIJHYVERIT, 4, VALTTULOANSVERO3, KUNNALLISVERO3, SAIRAUSVAKUUTUSMAKSU3, KELAVAKUUTUSMAKSU3, KIRKOLLISVERO3, 0);

%VahennJako&F(KIRKOLLISVERO4, VERO_VUOSI, ALIJHYVERIT, 5, VALTTULOANSVERO3, KUNNALLISVERO3, SAIRAUSVAKUUTUSMAKSU3, KELAVAKUUTUSMAKSU3, KIRKOLLISVERO3, 0);


ANSTULVEROT = VALTTULOANSVERO4 + KUNNALLISVERO4 + SAIRAUSVAKUUTUSMAKSU4 + KELAVAKUUTUSMAKSU4 + KIRKOLLISVERO4;

/* Varallisuusvero */

%VarallVeroS(VAVERO, VERO_VUOSI, INF, VERO_PUOLISO, VERO_LAPSIA, VERO_VAKASU, VERO_NETTOVARALL);

DROP taulua taulue;

* Valtionvero kattosäännön jälkeen;

%ValtVero_FinalS(VVKAT, VERO_VUOSI, YHTVALTVEROTULO, VALTTULOVERO, PAAOMAVERO2, (KUNNALLISVERO4 + SAIRAUSVAKUUTUSMAKSU4 + KELAVAKUUTUSMAKSU4 + KIRKOLLISVERO4));

VARVERKAT = MIN(VAVERO, VVKAT);

VALTTULVERKAT = VVKAT - VARVERKAT;

VALTTULVERANSKAT = MIN(VALTTULVERKAT, VALTTULOANSVERO4);
	
KAIKKIVEROT1 = KUNNALLISVERO4 + SAIRAUSVAKUUTUSMAKSU4 + KELAVAKUUTUSMAKSU4 + KIRKOLLISVERO4 + (VAVERO + VALTTULVERKAT);

IF VALTTULOVERO < VALTANSVAH THEN TEMPD = VALTANSVAH - VALTTULOVERO;
ELSE TEMPD = 0;

IF VERO_VUOSI < 2009 THEN TEMPE = MIN(TEMPD, KUNNALLISVERO4 + SAIRAUSVAKUUTUSMAKSU4 + KELAVAKUUTUSMAKSU4 + KIRKOLLISVERO4);
ELSE TEMPE = 0; 

KAIKKIVEROT2 = KUNNALLISVERO4 + SAIRAUSVAKUUTUSMAKSU4 + KELAVAKUUTUSMAKSU4 + KIRKOLLISVERO4 + (VALTTULOANSVERO4 + PAAOMAVERO2) - YHTHYVYHT - TEMPE;

/* Yle-Vero */

%YleVeroS(YLEVERO, VERO_VUOSI, INF, 30, SUM(PUHDANSTULO, PUHDPOTULO), 11); 

KAIKKIVEROT3 = SUM(KAIKKIVEROT2, PALKVAKMAKSU, SPMAKSU, YLEVERO);

VEROJENOSUUS = KAIKKIVEROT3 / KOKONTULO * 100;
	
NETTOTULOT = KOKONTULO - KAIKKIVEROT3;

%ValtTuloVero&F(TEMPF, VERO_VUOSI, INF, VALTVEROTULO);

IF TEMPF < VALTANSVAH THEN TEMPG = VALTANSVAH - TEMPF;
ELSE TEMPG = 0;

IF VERO_VUOSI < 2009 THEN TEMPH = TEMPG;
ELSE TEMPH = 0;

*Veronsaajien osuudet;

%YhtHyvJako&F(VALTIO1, 1, YHTHYVANS, YHTHYVPO, (VALTTULOANSVERO2 + PAAOMAVERO2), VALTTULOANSVERO4, KUNNALLISVERO4, SVMAKSU, 0, KIRKOLLISVERO4);
VALTIO = VALTIO1 - TEMPH;

%YhtHyvJako&F(KUNNAT, 2, YHTHYVANS, YHTHYVPO, (VALTTULOANSVERO2 + PAAOMAVERO2), VALTTULOANSVERO4, KUNNALLISVERO4, SVMAKSU, 0, KIRKOLLISVERO4);

%YhtHyvJako&F(KELA1, 3, YHTHYVANS, YHTHYVPO, (VALTTULOANSVERO2 + PAAOMAVERO2), VALTTULOANSVERO4, KUNNALLISVERO4, SVMAKSU, 0, KIRKOLLISVERO4);
KELA = SAIRAUSVAKUUTUSMAKSU4 + KELAVAKUUTUSMAKSU4 + SPMAKSU;

%YhtHyvJako&F(KIRKKO, 5, YHTHYVANS, YHTHYVPO, (VALTTULOANSVERO2 + PAAOMAVERO2), VALTTULOANSVERO4, KUNNALLISVERO4, SVMAKSU, 0, KIRKOLLISVERO4);

ELTTVAKLAIT = PALKVAKMAKSU;

VERONSYHT = VALTIO + KUNNAT + KELA + KIRKKO + ELTTVAKLAIT;

DROP taulua X taulue temp1 vahlapsia 
 	alijenimm elvakmaksux TEMPA TEMPB TEMPC TEMPD TEMPE TEMPF TEMPG TEMPH 
 	VALTIO1 KELA1 PA MUUANS2 SPM SPMY 
	VVKAT VARVERKAT VALTTULVERKAT VALTTULVERANSKAT ELAKELISAVERO;;

/* Yritystulon ja osinkotulon jakaminen */ 

* Yritystulon pääoma- ja ansiotulo-osuus;

%PomaOsuus&F(YTPOT, VERO_VUOSI, 1, VERO_VAIHT, VERO_YTULO, VERO_YRITVARALL, VERO_YPALKKA);
YTAT = MAX((VERO_YTULO - YTPOT), 0);

* Muusta kuin pörssiyhtiöstä saadun osingon ja siihen liittyvän yhtiöveron hyvityksen 
  pääomatulo- ja ansiotulo-osuus (1993 – 2004);

%PomaOsuus&F(OPOT, VERO_VUOSI, 2, 0, VERO_OTULO, VERO_YRITVARALL, 0);
OAT = MAX((VERO_OTULO - OPOT), 0);

%PomaOsuus&F(YVHYVPOT, VERO_VUOSI, 3, 0, VERO_OTULO, VERO_YRITVARALL, 0);

%YhtHyv&F(YVHY, VERO_VUOSI, VERO_OTULO);
YVHYVAT = MAX(YVHY, 0);

* Osinkojen jakaminen verottomiin tuloihin, pääomatuloihin ja ansiotuloihin (1993-);

%OsinkojenJako&F(OVT, VERO_VUOSI, INF, VERO_OSPKORKO, 1, VERO_JULKOSINKO, VERO_EIJULKOSINKO, VERO_OSAKKARVO);

%OsinkojenJako&F(OPO, VERO_VUOSI, INF, VERO_OSPKORKO, 2, VERO_JULKOSINKO, VERO_EIJULKOSINKO, VERO_OSAKKARVO);

%OsinkojenJako&F(OSAT, VERO_VUOSI, INF, VERO_OSPKORKO, 3, VERO_JULKOSINKO, VERO_EIJULKOSINKO, VERO_OSAKKARVO);
OYHT = OVT + OPO + OSAT;

DROP YVHY OPOT OAT ospkorverovap;


/* 4.2.7 Veromalli jos VERO_PUOLISO = 1 */

%IF &MINIMI_VERO_PUOLISO = 1 OR &MAKSIMI_VERO_PUOLISO = 1 %THEN %DO;
	IF VERO_PUOLISO = 1 THEN DO;

	* Johdettuja tulokäsitteitä ja vähennyksiä ym. (e/v);

	* Kokonaistulot;

	PKOKONTULO = (VERO_PPTULO + VERO_PPRAHATULO + VERO_PMTULO + VERO_PETULO + VERO_POPRAHA + VERO_POSANSTULO + VERO_PMUUANSTULO + VERO_POSINKOTULO + VERO_PVUOKRATULO + VERO_PKORKOTULO + VERO_PMUUPOTULO);

	* Ansiotulot (ilman yhtiöveron hyvitystä);

	PANSIOTULO = (VERO_PPTULO + VERO_PPRAHATULO + VERO_PMTULO + VERO_PETULO + VERO_POPRAHA + VERO_POSANSTULO + VERO_PMUUANSTULO);

	* Pääomatulot (ilman yhtiöveron hyvitystä);

	PPOTULO = (VERO_POSINKOTULO + VERO_PVUOKRATULO + VERO_PKORKOTULO + VERO_PMUUPOTULO);

	PPUHDPOTULO = PPOTULO - VERO_PPOVAHENN;

	%TulonHankKulut&F(PTULHANKSUMS, VERO_VUOSI, INF, VERO_PMTULO, VERO_PPTULO, VERO_PTULONHANKKULUT, VERO_PAYMAKSUT, VERO_PTYOMATKAKULUT, VERO_PKUUKAUDET);

	%AsuntoVahennys&F(PASUNTOVAH, VERO_VUOSI, INF, VERO_PKUUKAUDET, VERO_PVUOKRA);

	PPUHDASANSTULO = PANSIOTULO - (PTULHANKSUMS + PASUNTOVAH);

	IF PPUHDASANSTULO < 0 THEN PPUHDASANSTULO = 0;

	* Vähennykset vain valtionverotuksessa;

	%ValtElTulVah&F(PELVAHV, VERO_VUOSI, INF, VERO_PETULO, PPUHDASANSTULO, PKOKONTULO);

	%ValtTyoTuloVah&F(PVALTTVAH, VERO_VUOSI, INF, PANSIOTULO, VERO_PPTULO);

	* Vähennykset vain kunnallisverotuksessa;

	PMUAANS2 = MAX(PANSIOTULO - VERO_PETULO,0);

	%KunnAnsVah&F(PKUNNANS, VERO_VUOSI, INF, PPUHDASANSTULO, PMUAANS2, (VERO_PPTULO + VERO_PMTULO), VERO_PPTULO, PKOKONTULO);

	%KunnElTulVah&F(PELVELVAHK, VERO_VUOSI, INF, VERO_PUOLISO, 0, VERO_PETULO, PPUHDASANSTULO, PKOKONTULO);

	%KunnOpRahVah&F(POPRAHVAHK, VERO_VUOSI, INF, VERO_POPISK, VERO_POPRAHA, PANSIOTULO, PPUHDASANSTULO);

	%PalkVakMaksu&F(PPALKVAKMAKSU, VERO_VUOSI, VERO_PV53, VERO_PPTULO);

	%SvPrahaMaksu&F(PSPM, VERO_VUOSI, VERO_PPTULO);

	%SvPRahaMaksuY&F(PSPMY, VERO_VUOSI, 1, (VERO_POSINKOTULO));

	PSPMAKSU = PSPM + PSPMY;

	* Verotettava tulo kunnallisverotuksessa ennen perusvähennystä;

	%YhtHyv&F(PYHTHYVPO, VERO_VUOSI, VERO_POSINKOTULO);

	IF VERO_VUOSI < 1993 THEN PPA = PKOKONTULO + PYHTHYVPO - PTULHANKSUMS - VERO_PPOVAHENN;
	ELSE PPA = PPUHDASANSTULO;

	PKUNNVEROTULO = MAX(PPA - PPALKVAKMAKSU - PSPMAKSU - PKUNNANS - PELVELVAHK - POPRAHVAHK - VERO_PMUUVAHKUNN,0);

	IF PKUNNVEROTULO < 0 THEN PKUNNVEROTULO = 0;

	%KunnPerVah&F(PPERVAH, VERO_VUOSI, INF, PKUNNVEROTULO);

	*Verotettava tulo kunnallisverotuksessa;

	PKUNNVERTULOSP = MAX(PKUNNVEROTULO - PPERVAH,0);

	* Vähennyksiä veroista;

	%ValtVerAnsVah&F(PVALTANSVAH, VERO_VUOSI, INF,  (VERO_PPTULO + VERO_PMTULO + VERO_POSANSTULO), PPUHDASANSTULO);

	%ValtVerInvVah&F(PINVVAH, VERO_VUOSI, INF, VERO_PINVPROS, VERO_PETULO);

	%ValtVerElVelvVah&F(PVELVVAHV, VERO_VUOSI, INF, VERO_PEVLAPSIA, VERO_PELMAKSUT);

	%AlijHyv&F(PALIJHYV, VERO_VUOSI, INF, 1, VERO_LAPSIA, (PPOTULO + PYHTHYVPO), VERO_PPOVAHENN, 0, 0, 0, VERO_PPUOLALIJ);

	%AlijHyvErit&F(PALIJHYVERIT, VERO_VUOSI, INF, (PPOTULO + PYHTHYVPO), VERO_PPOVAHENN, 0, 0, VERO_ELVAKMAKSU);

	%KotiTalVah&F(PKOTIVAH, VERO_VUOSI, INF, VERO_PKOTITMENO);

	* Yhtiöveron hyvitys ;

	IF VERO_VUOSI > 1992 THEN DO;

		%YhtHyv&F(PYHTHYVANS, VERO_VUOSI, VERO_POSANSTULO);

	END;

	ELSE PYHTHYVANS = 0;

	%YhtHyv&F(PYHTHYVPO, VERO_VUOSI, VERO_POSINKOTULO);

	PYHTHYVYHT = PYHTHYVANS + PYHTHYVPO;

	IF VERO_VUOSI < 1993 THEN DO;
		PTEMPA = PKOKONTULO; 
   		PTEMPB = PYHTHYVPO;
	END;

	ELSE DO;
		PTEMPA = PANSIOTULO;
		PTEMPB = 0;
	END;
 
	PVALTVEROTULO = MAX(PTEMPA + PTEMPB + PYHTHYVANS - PTULHANKSUMS - PPALKVAKMAKSU - PSPMAKSU - PELVAHV - PVALTTVAH - VERO_PMUUVAHVALT,0); 

	IF PVALTVEROTULO < 0 THEN PVALTVEROTULO = 0;

	IF VERO_VUOSI < 1995 THEN PTEMPC = VERO_PKULKOROT;
	ELSE PTEMPC = 0;

	PVEROPOTULO = MAX(PPOTULO + PYHTHYVPO - VERO_PASKOROT, VERO_PENSASKOROT - VERO_PPOVAHENN - PTEMPC, 0); 

	IF VERO_VUOSI < 1993 THEN PYHTVALTVEROTULO = PVALTVEROTULO;
	ELSE PYHTVALTVEROTULO = PVALTVEROTULO + PVEROPOTULO;

	* Tuloverot ennen ansiotulovähennystä;

	%ValtTuloVero&F(PVALTTULOVERO, VERO_VUOSI, INF, PVALTVEROTULO);

	%ElakeLisaVero&F(PELAKELISAVERO, VERO_VUOSI, INF, VERO_PETULO, PELVAHV);

	PVALTTULOVERO = SUM(PVALTTULOVERO, PELAKELISAVERO);

	%KunnVero&F(PKUNNVERO, VERO_VUOSI, VERO_PKESKIM, VERO_PKUNNPROS, PKUNNVERTULOSP);

	%SairVakMaksu&F(PSVMAKSU, VERO_VUOSI, INF, PKUNNVERTULOSP, VERO_PETULO, (VERO_PPTULO + VERO_PMTULO));

	%KansElVakMaksu&F(PKEVMAKSU, VERO_VUOSI, PKUNNVERTULOSP, VERO_PETULO);

	IF VERO_PKIRKOSSA = 1 THEN DO;
		%KirkVero&F(PKIRKVEROS, VERO_VUOSI, VERO_PKESKIM, VERO_PKIRKPROS, PKUNNVERTULOSP);
	END;
	ELSE PKIRKVEROS = 0;

	%POTulonVeroErit&F(PPOTULOVERO, VERO_VUOSI, INF, VERO_POSINKOTULO, (VERO_PVUOKRATULO + VERO_PKORKOTULO + VERO_PMUUPOTULO), (VERO_PPOVAHENN + VERO_PASKOROT + VERO_PENSASKOROT), VERO_PKULKOROT, VERO_PELVAKMAKSU);

	* Tuloverot valtionverotuksen ansio/työtulovähennyksen jälkeen (jaetaan eri verolajeille, jos vuosi > 2008);

	IF VERO_VUOSI > 2008 THEN DO;

		%VahennJako&F(PVALTTULOANSVERO, VERO_VUOSI, PVALTANSVAH, 1, PVALTTULOVERO, PKUNNVERO, PSVMAKSU, PKEVMAKSU, PKIRKVEROS, 0);

		%VahennJako&F(PKUNNALLISVERO, VERO_VUOSI, PVALTANSVAH, 2, PVALTTULOVERO, PKUNNVERO, PSVMAKSU, PKEVMAKSU, PKIRKVEROS, 0);

		%VahennJako&F(PSAIRAUSVAKUUTUSMAKSU, VERO_VUOSI, PVALTANSVAH, 3, PVALTTULOVERO, PKUNNVERO, PSVMAKSU, PKEVMAKSU, PKIRKVEROS, 0);

		%VahennJako&F(PKELAVAKUUTUSMAKSU, VERO_VUOSI, PVALTANSVAH, 4, PVALTTULOVERO, PKUNNVERO, PSVMAKSU, PKEVMAKSU, PKIRKVEROS, 0);

		%VahennJako&F(PKIRKOLLISVERO, VERO_VUOSI, PVALTANSVAH, 5, PVALTTULOVERO, PKUNNVERO, PSVMAKSU, PKEVMAKSU, PKIRKVEROS, 0);
	
	END;

	ELSE DO;

		PVALTTULOANSVERO = MAX(PVALTTULOVERO - PVALTANSVAH, 0);

		PKUNNALLISVERO = PKUNNVERO;

		PSAIRAUSVAKUUTUSMAKSU = PSVMAKSU;

		PKELAVAKUUTUSMAKSU = PKEVMAKSU;

		PKIRKOLLISVERO = PKIRKVEROS;

	END;

	* Valtion tulovero invalidi- ja ansiotulovähennyksen jälkeen;

	PVALTTULOINV = MAX(PVALTTULOANSVERO - PINVVAH - PVELVVAHV, 0);

	* Tuloverot kotitalousvähennyksen jälkeen;

	%VahennJako&F(PVALTTULOANSVERO2, VERO_VUOSI, PKOTIVAH, 1, PVALTTULOINV, PKUNNALLISVERO, PSAIRAUSVAKUUTUSMAKSU, PKELAVAKUUTUSMAKSU, PKIRKOLLISVERO, PPOTULOVERO);

	%VahennJako&F(PKUNNALLISVERO2, VERO_VUOSI, PKOTIVAH, 2, PVALTTULOINV, PKUNNALLISVERO, PSAIRAUSVAKUUTUSMAKSU, PKELAVAKUUTUSMAKSU, PKIRKOLLISVERO, PPOTULOVERO);

	%VahennJako&F(PSAIRAUSVAKUUTUSMAKSU2, VERO_VUOSI, PKOTIVAH, 3, PVALTTULOINV, PKUNNALLISVERO, PSAIRAUSVAKUUTUSMAKSU, PKELAVAKUUTUSMAKSU, PKIRKOLLISVERO, PPOTULOVERO);

	%VahennJako&F(PKELAVAKUUTUSMAKSU2, VERO_VUOSI, PKOTIVAH, 4, PVALTTULOINV, PKUNNALLISVERO, PSAIRAUSVAKUUTUSMAKSU, PKELAVAKUUTUSMAKSU, PKIRKOLLISVERO, PPOTULOVERO);

	%VahennJako&F(PKIRKOLLISVERO2, VERO_VUOSI, PKOTIVAH, 5, PVALTTULOINV, PKUNNALLISVERO, PSAIRAUSVAKUUTUSMAKSU, PKELAVAKUUTUSMAKSU, PKIRKOLLISVERO, PPOTULOVERO);

	%VahennJako&F(PPAAOMAVERO2, VERO_VUOSI, PKOTIVAH, 6, PVALTTULOINV, PKUNNALLISVERO, PSAIRAUSVAKUUTUSMAKSU, PKELAVAKUUTUSMAKSU, PKIRKOLLISVERO, PPOTULOVERO);

	* Tuloverot alijäämähyvityksen jälkeen;

	%AlijHyvJako&F(PVALTTULOANSVERO3, VERO_VUOSI, 1, PALIJHYV, PVALTTULOANSVERO2, PKUNNALLISVERO2, PSAIRAUSVAKUUTUSMAKSU2, PKELAVAKUUTUSMAKSU2, PKIRKOLLISVERO2);

	%AlijHyvJako&F(PKUNNALLISVERO3, VERO_VUOSI, 2, PALIJHYV, PVALTTULOANSVERO2, PKUNNALLISVERO2, PSAIRAUSVAKUUTUSMAKSU2, PKELAVAKUUTUSMAKSU2, PKIRKOLLISVERO2);

	%AlijHyvJako&F(PSAIRAUSVAKUUTUSMAKSU3, VERO_VUOSI, 3, PALIJHYV, PVALTTULOANSVERO2, PKUNNALLISVERO2, PSAIRAUSVAKUUTUSMAKSU2, PKELAVAKUUTUSMAKSU2, PKIRKOLLISVERO2);

	%AlijHyvJako&F(PKELAVAKUUTUSMAKSU3, VERO_VUOSI, 4, PALIJHYV, PVALTTULOANSVERO2, PKUNNALLISVERO2, PSAIRAUSVAKUUTUSMAKSU2, PKELAVAKUUTUSMAKSU2, PKIRKOLLISVERO2);

	%AlijHyvJako&F(PKIRKOLLISVERO3, VERO_VUOSI, 5, PALIJHYV, PVALTTULOANSVERO2, PKUNNALLISVERO2, PSAIRAUSVAKUUTUSMAKSU2, PKELAVAKUUTUSMAKSU2, PKIRKOLLISVERO2);

	* Tuloverot erityisen alijäämähyvityksen jälkeen; 

	%VahennJako&F(PVALTTULOANSVERO4, VERO_VUOSI, PALIJHYVERIT, 1, PVALTTULOANSVERO3, PKUNNALLISVERO3, PSAIRAUSVAKUUTUSMAKSU3, 0, PKIRKOLLISVERO3, PVALTTULOANSVERO3);

	%VahennJako&F(PKUNNALLISVERO4, VERO_VUOSI, PALIJHYVERIT, 2, PVALTTULOANSVERO3, PKUNNALLISVERO3, PSAIRAUSVAKUUTUSMAKSU3, 0, PKIRKOLLISVERO3, PVALTTULOANSVERO3);

	%VahennJako&F(PSAIRAUSVAKUUTUSMAKSU4, VERO_VUOSI, PALIJHYVERIT, 3, PVALTTULOANSVERO3, PKUNNALLISVERO3, PSAIRAUSVAKUUTUSMAKSU3, 0, PKIRKOLLISVERO3, PVALTTULOANSVERO3);

	%VahennJako&F(PKELAVAKUUTUSMAKSU4, VERO_VUOSI, PALIJHYVERIT, 4, PVALTTULOANSVERO3, PKUNNALLISVERO3, PSAIRAUSVAKUUTUSMAKSU3, 0, PKIRKOLLISVERO3, PVALTTULOANSVERO3);

	%VahennJako&F(PKIRKOLLISVERO4, VERO_VUOSI, PALIJHYVERIT, 5, PVALTTULOANSVERO3, PKUNNALLISVERO3, PSAIRAUSVAKUUTUSMAKSU3, 0, PKIRKOLLISVERO3, PVALTTULOANSVERO3);

	* Ansiotulojen verot (1993–) tai tuloverot yhteensä;

	PANSTULVEROT = PVALTTULOANSVERO4 + PKUNNALLISVERO4 + PSAIRAUSVAKUUTUSMAKSU4 + PKELAVAKUUTUSMAKSU4 + PKIRKOLLISVERO4;

	/* Varallisuusvero */

	%VarallVeroS(PVAVERO, VERO_VUOSI, INF, 1, VERO_LAPSIA, VERO_PVAKASU, VERO_PNETTOVARALL);

	DROP taulua taulue;

	* Valtionvero kattosäännön jälkeen;

	%ValtVero_FinalS(PVVKAT, VERO_VUOSI, PYHTVALTVEROTULO, PVALTTULOVERO, PPAAOMAVERO2, (PKUNNALLISVERO4 + PSAIRAUSVAKUUTUSMAKSU4 + PKELAVAKUUTUSMAKSU4 + PKIRKOLLISVERO4));

	PVARVERKAT = MIN(PVAVERO, PVVKAT);

	PVALTTULVERKAT = PVVKAT - PVARVERKAT;

	PVALTTULVERANSKAT = MIN(PVALTTULVERKAT, PVALTTULOANSVERO4);
	
	PKAIKKIVEROT1 = PKUNNALLISVERO4 + PSAIRAUSVAKUUTUSMAKSU4 + PKELAVAKUUTUSMAKSU4 + PKIRKOLLISVERO4 + (PVAVERO + PVALTTULVERKAT);

	IF PVALTTULOVERO < PVALTANSVAH THEN PTEMPD = PVALTANSVAH - PVALTTULOVERO;
	ELSE PTEMPD = 0;

	IF VERO_VUOSI < 2009 THEN PTEMPE = MIN(PTEMPD, PKUNNALLISVERO4 + PSAIRAUSVAKUUTUSMAKSU4 + PKELAVAKUUTUSMAKSU4 + PKIRKOLLISVERO4);
	ELSE PTEMPE = 0; 

	PKAIKKIVEROT2 = PKUNNALLISVERO4 + PSAIRAUSVAKUUTUSMAKSU4 + PKELAVAKUUTUSMAKSU4 + PKIRKOLLISVERO4 + (PVALTTULOANSVERO4 + PPAAOMAVERO2) - PYHTHYVYHT - PTEMPE;

	/* Yle-Vero */

	%YleVeroS(PYLEVERO, VERO_VUOSI, INF, 30, SUM(PPUHDASANSTULO, PPUHDPOTULO), 11); 

	PKAIKKIVEROT3 = SUM(PKAIKKIVEROT2, PPALKVAKMAKSU, PSPMAKSU, PYLEVERO);

	PVEROJENOSUUS = PKAIKKIVEROT3 / PKOKONTULO * 100; 

	PNETTOTULOT = PKOKONTULO - PKAIKKIVEROT3;

	%ValtTuloVero&F(PTEMPF, VERO_VUOSI, INF, PVALTVEROTULO);

	IF PTEMPF < PVALTANSVAH THEN PTEMPG = PVALTANSVAH - PTEMPF;
	ELSE PTEMPG = 0;

	IF VERO_VUOSI < 2009 THEN PTEMPH = PTEMPG;
	ELSE PTEMPH = 0;

	%YhtHyvJako&F(PVALTIO1, 1, PYHTHYVANS, PYHTHYVPO, (PVALTTULOANSVERO2 + PPAAOMAVERO2), PVALTTULOANSVERO4, PKUNNALLISVERO4, PSVMAKSU, 0, PKIRKOLLISVERO4);
	PVALTIO = PVALTIO1 - PTEMPH;

	%YhtHyvJako&F(PKUNNAT, 2, PYHTHYVANS, PYHTHYVPO, (PVALTTULOANSVERO2 + PPAAOMAVERO2), PVALTTULOANSVERO4, PKUNNALLISVERO4, PSVMAKSU, 0, PKIRKOLLISVERO4);

	%YhtHyvJako&F(PKELA1, 3, PYHTHYVANS, PYHTHYVPO, (PVALTTULOANSVERO2 + PPAAOMAVERO2), PVALTTULOANSVERO4, PKUNNALLISVERO4, PSVMAKSU, 0, PKIRKOLLISVERO4);
	PKELA = PKELA1 + PSPMAKSU;

	%YhtHyvJako&F(PKIRKKO, 5, PYHTHYVANS, PYHTHYVPO, (PVALTTULOANSVERO2 + PPAAOMAVERO2), PVALTTULOANSVERO4, PKUNNALLISVERO4, PSVMAKSU, 0, PKIRKOLLISVERO4);

	PELTTVAKLAIT = PPALKVAKMAKSU;

	PVERONSYHT = PVALTIO + PKUNNAT + PKELA + PKIRKKO + PELTTVAKLAIT;

	* Puolisot yhteensä;

	BRUTTOTULOT = KOKONTULO + PKOKONTULO;
	VEROTYHT = KAIKKIVEROT3 + PKAIKKIVEROT3;
	VEROJENOSTUL = (VEROTYHT / BRUTTOTULOT) * 100;
	NETTULOT = BRUTTOTULOT - VEROTYHT;

	DROP taulua X taulue temp1 elvakmaksux PTEMPA PTEMPB PTEMPC 
		PTEMPD PTEMPE PTEMPF PTEMPG PTEMPH PVALTIO1 PKELA1 PPA PSPM PSPMY PMUAANS2
		PVVKAT PVARVERKAT PVALTTULVERKAT PVALTTULVERANSKAT PELAKELISAVERO;
END;
%END;

RUN;

%MEND Vero_Simuloi_Esimerkki;

%Vero_Simuloi_Esimerkki;


/* 4.3 Lasketaan marginaaliveroaste */

%MACRO Vero_Simuloi_MargVero;

/* 4.3.1 Otetaan talteen alkuperäiset tulokset ja nimetään 
         laskennassa tarvittava verotieto uudelleen */

DATA TEMP.VERO_ESIM_MARGVERO ;
SET OUTPUT.&TULOSNIMI_VE;
VEROT = KAIKKIVEROT3;
RUN;

/* 4.3.2 Simuloidaan veromalli uudestaan lisäämällä palkkatuloihin askeleen mukainen palkanlisä */

%Generoi_Muuttujat;

DATA OUTPUT.&TULOSNIMI_VE;
SET OUTPUT.&TULOSNIMI_VE;
VERO_PTULO = SUM(VERO_PTULO, VERO_ASKEL);
RUN;

%Vero_Simuloi_Esimerkki;

/* 4.3.3 Otetaan talteen uudelleen simuloidut tulokset ja nimetään 
         laskennassa tarvittava verotieto uudelleen */

DATA OUTPUT.&TULOSNIMI_VE;
SET OUTPUT.&TULOSNIMI_VE;
VEROT2 = KAIKKIVEROT3;
KEEP VEROT2;
RUN;

/* 4.3.4 Lasketaan marginaaliveroaste ja efektiivinen marginaaliveroaste */

DATA OUTPUT.&TULOSNIMI_VE;
MERGE OUTPUT.&TULOSNIMI_VE  TEMP.VERO_ESIM_MARGVERO ;
MARGIVERO = 100 * (SUM(VEROT2, - VEROT) / VERO_ASKEL);

DROP VEROT VEROT2;

/* 4.4 Määritellään muuttujille selkokieliset selitteet */

LABEL 
VERO_VUOSI = 'Lainsäädäntövuosi'
VERO_PTULO = 'Palkkatulo, e/v'
VERO_MTULO = 'Muu työtulo kuin palkkatulo, e/v'
VERO_PRAHATULO = 'Päivärahatulo, e/v'
VERO_ETULO = 'Eläketulo, e/v'
VERO_OPRAHA = 'Opintoraha, e/v'
VERO_OSANSTULO = 'Osinkotulo ansiotulona, e/v' 
VERO_MUUANSTULO = 'Muu ansiotulo, e/v'
VERO_OSINKOTULO = 'Osinkotulo pääomatulona, e/v'
VERO_VUOKRATULO = 'Vuokratulot vakituisesta asunnosta, e/v'
VERO_KORKOTULO = 'Veronalaiset korkotulot, e/v'
VERO_MUUPOTULO = 'Muu pääomatulo, e/v'
VERO_NETTOPALKKA = 'Nettopalkka, e/kk'
VERO_ASKEL = 'Tuloaskel, jolla tuloa korotetaan marginaaliveroastetta laskettaessa, e/v'
VERO_VAKASU = 'Vakituinen asunto varallisuuden osana (0/1)'
VERO_NETTOVARALL = 'Nettovarallisuus, e'

VERO_TULONHANKKULUT = 'Tulonhankkimiskulut, e/v' 
VERO_AYMAKSUT = 'Ay-jäsenmaksut, e/v' 
VERO_TYOMATKAKULUT = 'Työmatkakulut, e/v' 
VERO_KUUKAUDET = 'Työasuntovähennykseen oikeuttavat kuukaudet' 
VERO_VUOKRA = 'Työasuntovähennykseen oikeuttava vuokra, e/kk' 
VERO_ELMAKSUT = 'Elatusmaksut, e/v'
VERO_POVAHENN = 'Pääomatulon hankkimisesta aiheuttavat menot, e/v'  
VERO_ASKOROT = 'Asunto- ja opintolainan korot, e/v'
VERO_ENSASKOROT = 'Ensiasuntoon kohdistuvan luoton korot, e/v'
VERO_KULKOROT = 'Kulutusluoton korot, e/v'
VERO_ELVAKMAKSU = 'Pääomatuloista vähennettäva vap.eht. eläkevakuutusmaksu (2005-), e/v'
VERO_SAIRKULUT = 'Sairauskulut, e/v'
VERO_KOTITMENO = 'Kotitalousvähennykseen oikeuttavat menot, e/v'
VERO_MUUVAHVALT = 'Muita vähennyksiä tulosta valtionverotuksessa, e/v'
VERO_MUUVAHKUNN = 'Muita vähennyksiä tulosta kunnallisverotuksessa, e/v'

VERO_PUOLISO = 'Onko puolisoa (0/1)'
VERO_V53 = '53 vuotta täyttänyt (0/1)'
VERO_LAPSIA = 'Huollettavina olevien alaikäisten lasten lkm'
VERO_EVLAPSIA = 'Elatusvellvollisten lasten lkm'
VERO_OPISK = 'Onko opiskelija (0/1)'
VERO_YRIT = 'Onko opiskelija (0/1)'
VERO_INVPROS = 'Vamman haitta-aste (1-100)'
VERO_TYOTKUUK = 'Työttömyyskuukaudet'
VERO_PUOLALIJ = 'Puolison alijäämähyvitys, e/v'
VERO_KUNNPROS = 'Kunnallinen veroprosentti (jos ei automaattisesti keskiarvo)'
VERO_KIRKPROS = 'Kirkollinen veroprosentti (jos ei automaattisesti keskiarvo)'
VERO_KESKIM = 'Käytetäänkö keskimääräistä kunnallis-, ja kirkollisveroprosenttia (0/1)'
VERO_KIRKOSSA = 'Kuuluuko kirkkoon (0/1)'

VERO_VAIHT = 'Yritystulon ja osinkotulon jakaminen (1993–): Vaihtoehtoinen alempi osuus, (0/1)'
VERO_YTULO = 'Yritystulon ja osinkotulon jakaminen (1993–): Jaettava yritystulo, e/v'
VERO_YRITVARALL = 'Yritystulon ja osinkotulon jakaminen (1993–): Yritysvarallisuus/Osakkeiden arvo, e'
VERO_YPALKKA = 'Yritystulon ja osinkotulon jakaminen (1993–): Yrityksessä maksetut palkat, e/v'
VERO_OTULO = 'Yritystulon ja osinkotulon jakaminen (1993–): Osinkotulo, e/v'
VERO_OSPKORKO = 'Yritystulon ja osinkotulon jakaminen (1993–): Osuuspääoman korkoa? (0/1)'
VERO_JULKOSINKO = 'Yritystulon ja osinkotulon jakaminen (1993–): Osinko julk.not yhtiöstä, e/v'
VERO_EIJULKOSINKO = 'Yritystulon ja osinkotulon jakaminen (1993–): Muu osinko, e/v'
VERO_OSAKKARVO = 'Yritystulon ja osinkotulon jakaminen (1993–): Muiden osakkeiden matemaattinen arvo, e'

TULOVERO = 'Yksinkertainen malli: Tulovero'
BRUTTOTULO = 'Yksinkertainen malli: Nettokuukausitulosta johdettu bruttotulo '
MARGINAALIVEROASTE = 'Yksinkertainen malli: Marginaaliveroaste, %'
TULOVERO_ELAKE = 'Yksinkertainen malli: Eläketulon verot'
TULOVERO_PRAHA = 'Yksinkertainen malli: Tuloverot kun tulot ovat työttömyysturvaa tai muuta vastaavaa sosiaalietuutta'
VOSUUSPTULO = 'Yksinkertainen malli: Verojen osuus palkkatuloista, %'
VOSUUSNKTULO = 'Verojen osuus - Käänteisfunktio: nettokuukausituloa vastaava bruttokuukausitulo, %'
VOSUUSETULO = 'Yksinkertainen malli: Verojen osuus eläketulosta, %'
VOSUUSPRAHATULO = 'Yksinkertainen malli: Verojen osuus päivärahatulosta, %'

KOKONTULO = 'Kokonaistulot'
ANSIOTULO = 'Ansiotulot (ilman yhtiöveron hyvitystä)'
POTULO = 'Pääomatulot (ilman yhtiöveron hyvitystä)'
PUHDPOTULO = 'Puhdas pääomatulo'
TULHANKSUMS = 'Tulonhankkimiskulut (ml. tulonhankkimisvähennys, ay-maksut, työmatkakulut)'
ASUNTOVAH = 'Työasuntovähennys'
PUHDANSTULO = 'Puhdas ansiotulo'
ELVAHV = 'Valtionverotuksen eläketulovähennys'
VALTTVAH = 'Valtionverotuksen työtulovähennys ja palkkavähennys'
KUNNANS = 'Kunnallisverotuksen ansiotulovähennys'
ELVELVAHK = 'Kunnallisverotuksen eläketulovähennys'
OPRAHVAHK = 'Kunnallisverotuksen opintorahavähennys'
PALKVAKMAKSU = 'Palkansaajan vakuutusmaksut '
SPMAKSU = 'Sairausvakuutuksen päivärahamaksu'
KUNNVEROTULO = 'Verotettava tulo kunnallisverotuksessa ennen perusvähennystä'
PERVAH = 'Kunnallisverotuksen perusvähennys'
KUNNVERTULOSP = 'Verotettava tulo kunnallisverotuksessa'
VALTANSVAH = 'Ansiotulovähennys valtionverosta'
INVVAH = 'Invalidivähennys valtionverosta (ja vanhuusvähennys)' 
VELVVAHV = 'Elatusvelvollisuusvähennys valtion verosta'
ALIJHYV = 'Alijäämähyvitys yhteensä'
ALIJHYVERIT = 'Erityinen alijäämähyvitys'
KOTIVAH = 'Kotitalousvähennys'
YHTHYVANS = 'Yhtiöveron hyvitys ansiotulona (ansiotulo-osingosta)'
YHTHYVPO = 'Yhtiöveron hyvitys pääomatulona (pääomatulo-osingosta)'
YHTHYVYHT = 'Yhtiöveron hyvitys'
VALTVEROTULO = 'Valtionverotuksessa verotettava tulo (–1992) tai ansiotulo (1993–)'
VEROPOTULO = 'Verotettava pääomatulo (1993–)'
YHTVALTVEROTULO = 'Verotettava tulo valtionverotuksessa yhteensä'

VALTTULOVERO = 'Valtion tulovero (–1992) tai ansiotulojen valtionvero (1993–)'
KUNNVERO = 'Kunnallisvero'
SVMAKSU = 'Sairausvakuutusmaksu/sairaanhoitomaksu'
KEVMAKSU = 'Kansaneläkevakuutusmaksu '
KIRKVEROS = 'Kirkollisvero'
POTULOVERO = 'Pääomatulon vero'

VALTTULOANSVERO = 'Ansiotulojen valtionvero ansio/työtulovähennyksen jälkeen'
KUNNALLISVERO = 'Kunnallisvero ansio/työtulovähennyksen jälkeen'
SAIRAUSVAKUUTUSMAKSU = 'Sairausvakuutusmaksu ansio/työtulovähennyksen jälkeen'
KELAVAKUUTUSMAKSU = 'Kansaneläkevakuutusmaksu ansio/työtulovähennyksen jälkeen'
KIRKOLLISVERO = 'Kirkollisvero ansio/työtulovähennyksen jälkeen'

VALTTULOINV = 'Valtion tulovero invalidi- ja ansiotulovähennyksen jälkeen'

VALTTULOANSVERO2 = 'Ansiotulojen valtionvero kotitalousvähennyksen jälkeen'
KUNNALLISVERO2 = 'Kunnallisvero kotitalousvähennyksen jälkeen'
SAIRAUSVAKUUTUSMAKSU2 = 'Sairausvakuutusmaksu kotitalousvähennyksen jälkeen'
KELAVAKUUTUSMAKSU2 = 'Kansaneläkevakuutusmaksu kotitalousvähennyksen jälkeen'
KIRKOLLISVERO2 = 'Kirkollisvero kotitalousvähennyksen jälkeen'
PAAOMAVERO2 = 'Pääomatulon vero kotitalousvähennyksen jälkeen'

VALTTULOANSVERO3 = 'Ansiotulojen valtionvero alijäämähyvityksen jälkeen'
KUNNALLISVERO3 = 'Kunnallisvero alijäämähyvityksen jälkeen'
SAIRAUSVAKUUTUSMAKSU3 = 'Sairausvakuutusmaksu alijäämähyvityksen jälkeen'
KELAVAKUUTUSMAKSU3 = 'Kansaneläkevakuutusmaksu alijäämähyvityksen jälkeen'
KIRKOLLISVERO3 = 'Kirkollisvero alijäämähyvityksen jälkeen'

VALTTULOANSVERO4 = 'Ansiotulojen valtionvero erityisen alijäämähyvityksen jälkeen'
KUNNALLISVERO4 = 'Kunnallisvero erityisen alijäämähyvityksen jälkeen'
SAIRAUSVAKUUTUSMAKSU4 = 'Sairausvakuutusmaksu erityisen alijäämähyvityksen jälkeen'
KELAVAKUUTUSMAKSU4 = 'Kansaneläkevakuutusmaksu erityisen alijäämähyvityksen jälkeen'
KIRKOLLISVERO4 = 'Kirkollisvero erityisen alijäämähyvityksen jälkeen'

ANSTULVEROT = 'Ansiotulojen verot (1993–) tai tuloverot yhteensä'
VAVERO = 'Varallisuusvero (1993-2005)'
KAIKKIVEROT1 = 'Kaikki verot kattosäännön jälkeen'
KAIKKIVEROT2 = 'Verot yhtiöveron hyvityksen ja valtionverotuksen ans.tuloväh. (ennen 2009) jälkeen'
YLEVERO = 'Yle-vero (2013-)'
KAIKKIVEROT3 = 'Kaikki verot (ml. palkansaajan vakmaksut ja Yle-vero))'
VEROJENOSUUS = 'Verojen osuus tuloista, %'
NETTOTULOT = 'Nettotulo'

VALTIO = 'Veronsaajien osuudet: Valtio'
KUNNAT = 'Veronsaajien osuudet: Kunnat'
KELA = 'Veronsaajien osuudet: KELA'
KIRKKO = 'Veronsaajien osuudet: Kirkko'
ELTTVAKLAIT = 'Veronsaajien osuudet: Eläke- ja työttömyysvakuutuslaitokset'
VERONSYHT = 'Veronsaajien osuudet yhteensä'

YTPOT = 'Yritystulosta pääomatuloa'
YTAT = 'Yritystulosta ansiotuloa'
YVHYVPOT = 'Yhtiöveron hyvityksestä pääomatuloa'
YVHYVAT = 'Yhtiöveron hyvityksestä ansiotuloa'
OVT = 'Osingoista verotonta tuloa'
OPO = 'Osingoista pääomatuloa'
OSAT = 'Osingoista ansiotuloa'
OYHT = 'Osingot yhteensä'

MARGIVERO = 'Marginaaliveroaste, %'

/* 4.4 Määritellään puolison muuttujille selkokieliset selitteet (jos VERO_PUOLISO = 1) */

%IF &MINIMI_VERO_PUOLISO = 1 OR &MAKSIMI_VERO_PUOLISO = 1 %THEN %DO;

VERO_PPTULO = 'Puoliso: Palkkatulo, e/v'
VERO_PMTULO = 'Puoliso: Muu työtulo kuin palkkatulo, e/v'
VERO_PPRAHATULO = 'Puoliso: Päivärahatulo, e/v'
VERO_PETULO = 'Puoliso: Eläketulo, e/v'
VERO_POPRAHA = 'Puoliso: Opintoraha, e/v'
VERO_POSANSTULO = 'Puoliso: Osinkotulo ansiotulona, e/v' 
VERO_PMUUANSTULO = 'Puoliso: Muu ansiotulo, e/v'
VERO_POSINKOTULO = 'Puoliso: Osinkotulo pääomatulona, e/v'
VERO_PVUOKRATULO = 'Puoliso: Vuokratulot vakituisesta asunnosta, e/v'
VERO_PKORKOTULO = 'Puoliso: Veronalaiset korkotulot, e/v'
VERO_PMUUPOTULO = 'Puoliso: Muu pääomatulo, e/v'
VERO_PVAKASU = 'Puoliso: Vakituinen asunto varallisuuden osana (0/1)'
VERO_PNETTOVARALL = 'Puoliso: Nettovarallisuus, e'

VERO_PTULONHANKKULUT = 'Puoliso: Tulonhankkimiskulut, e/v' 
VERO_PAYMAKSUT = 'Puoliso: Ay-jäsenmaksut, e/v' 
VERO_PTYOMATKAKULUT = 'Puoliso: Työmatkakulut, e/v' 
VERO_PKUUKAUDET = 'Puoliso: Työasuntovähennykseen oikeuttavat kuukaudet' 
VERO_PVUOKRA = 'Puoliso: Työasuntovähennykseen oikeuttava vuokra, e/kk' 
VERO_PELMAKSUT = 'Puoliso: Elatusmaksut, e/v'
VERO_PPOVAHENN = 'Puoliso: Pääomatulon hankkimisesta aiheuttavat menot, e/v'  
VERO_PASKOROT = 'Puoliso: Asunto- ja opintolainan korot, e/v'
VERO_PENSASKOROT = 'Puoliso: Ensiasuntoon kohdistuvan luoton korot, e/v'
VERO_PKULKOROT = 'Puoliso: Kulutusluoton korot, e/v'
VERO_PELVAKMAKSU = 'Puoliso: Pääomatuloista vähennettäva vap.eht. eläkevakuutusmaksu (2005-), e/v'
VERO_PKOTITMENO = 'Puoliso: Kotitalousvähennykseen oikeuttavat menot, e/v'
VERO_PMUUVAHVALT = 'Puoliso: Muita vähennyksiä tulosta valtionverotuksessa, e/v'
VERO_PMUUVAHKUNN = 'Puoliso: Muita vähennyksiä tulosta kunnallisverotuksessa, e/v'

VERO_PV53 = 'Puoliso: 53-v. täyttänyt (0/1)'
VERO_PEVLAPSIA = 'Puoliso: Elatusvellvollisten lasten lkm'
VERO_POPISK = 'Puoliso: Onko opiskelija (0/1)'
VERO_PYRIT = 'Puoliso: Onko yrittäjä (0/1)'
VERO_PINVPROS = 'Puoliso: Vamman haitta-aste (1-100)'
VERO_PTYOTKUUK = 'Puoliso: Työttömyyskuukaudet'
VERO_PPUOLALIJ = 'Puoliso: Puolison alijäämähyvitys, e/v'
VERO_PKUNNPROS = 'Puoliso: Kunnallinen veroprosentti (jos ei automaattisesti keskiarvo)'
VERO_PKIRKPROS = 'Puoliso: Kirkollinen veroprosentti (jos ei automaattisesti keskiarvo)'
VERO_PKESKIM = 'Puoliso: Käytetäänkö keskimääräistä kunnallis-, ja kirkollisveroprosenttia (0/1)'
VERO_PKIRKOSSA = 'Puoliso: Kuuluuko kirkkoon (0/1)'

PKOKONTULO = 'Puoliso: Kokonaistulot'
PANSIOTULO = 'Puoliso: Ansiotulot (ilman yhtiöveron hyvitystä)'
PPOTULO = 'Puoliso: Pääomatulot (ilma yhtiöveron hyvitystä)'
PPUHDPOTULO = 'Puoliso: Puhdas pääomatulo'
PTULHANKSUMS = 'Puoliso: Tulonhankkimiskulut (ml. tulonhankkimisvähennys, ay-maksut, työmatkakulut)'
PASUNTOVAH = 'Puoliso: Työasuntovähennys'
PPUHDASANSTULO = 'Puoliso: Puhdas ansiotulo'
PELVAHV = 'Puoliso: Valtionverotuksen eläketulovähennys'
PVALTTVAH = 'Puoliso: Valtionverotuksen työtulovähennys ja palkkavähennys'
PKUNNANS = 'Puoliso: Kunnallisverotuksen ansiotulovähennys'
PELVELVAHK = 'Puoliso: Kunnallisverotuksen elatusvelvollisuusvähennys'
POPRAHVAHK = 'Puoliso: Kunnallisverotuksen opintorahavähennys'
PPALKVAKMAKSU = 'Puoliso: Palkansaajan vakuutusmaksut '
PSPMAKSU = 'Puoliso: Sairausvakuutuksen päivärahamaksu'
PKUNNVEROTULO = 'Puoliso: Verotettava tulo kunnallisverotuksessa ennen perusvähennystä'
PPERVAH = 'Puoliso: Kunnallisverotuksen perusvähennys'
PKUNNVERTULOSP = 'Puoliso: Verotettava tulo kunnallisverotuksessa'
PVALTANSVAH = 'Puoliso: Ansiotulovähennys valtionverosta'
PINVVAH = 'Puoliso: Invalidivähennys valtionverosta (ja vanhuusvähennys)' 
PVELVVAHV = 'Puoliso: Elatusvelvollisuusvähennys valtion verosta'
PALIJHYV = 'Puoliso: Alijäämähyvitys yhteensä'
PALIJHYVERIT = 'Puoliso: Erityinen alijäämähyvitys'
PKOTIVAH = 'Puoliso: Kotitalousvähennys'
PYHTHYVANS = 'Puoliso: Yhtiöveron hyvitys ansiotulona (ansiotulo-osingosta)'
PYHTHYVPO = 'Puoliso: Yhtiöveron hyvitys pääomatulona (pääomatulo-osingosta)'
PYHTHYVYHT = 'Puoliso: Yhtiöveron hyvitys'
PVALTVEROTULO = 'Puoliso: Valtionverotuksessa verotettava tulo (–1992) tai ansiotulo (1993–)'
PVEROPOTULO = 'Puoliso: Verotettava pääomatulo (1993–)'
PYHTVALTVEROTULO = 'Puoliso: Verotettava tulo valtionverotuksessa yhteensä'

PVALTTULOVERO = 'Puoliso: Valtion tulovero (–1992) tai ansiotulojen valtionvero (1993–)'
PKUNNVERO = 'Puoliso: Kunnallisvero'
PSVMAKSU = 'Puoliso: Sairausvakuutusmaksu/sairaanhoitomaksu'
PKEVMAKSU = 'Puoliso: Kansaneläkevakuutusmaksu '
PKIRKVEROS = 'Puoliso: Kirkollisvero'
PPOTULOVERO = 'Puoliso: Pääomatulon vero'

PVALTTULOANSVERO = 'Puoliso: Ansiotulojen valtionvero ansio/työtulovähennyksen jälkeen'
PKUNNALLISVERO = 'Puoliso: Kunnallisvero ansio/työtulovähennyksen jälkeen'
PSAIRAUSVAKUUTUSMAKSU = 'Puoliso: Sairausvakuutusmaksu ansio/työtulovähennyksen jälkeen'
PKELAVAKUUTUSMAKSU = 'Puoliso: Kansaneläkevakuutusmaksu ansio/työtulovähennyksen jälkeen'
PKIRKOLLISVERO = 'Puoliso: Kirkollisvero ansio/työtulovähennyksen jälkeen'

PVALTTULOINV = 'Puoliso: Valtion tulovero invalidi- ja ansiotulovähennyksen jälkeen'

PVALTTULOANSVERO2 = 'Puoliso: Ansiotulojen valtionvero kotitalousvähennyksen jälkeen'
PKUNNALLISVERO2 = 'Puoliso: Kunnallisvero kotitalousvähennyksen jälkeen'
PSAIRAUSVAKUUTUSMAKSU2 = 'Puoliso: Sairausvakuutusmaksu kotitalousvähennyksen jälkeen'
PKELAVAKUUTUSMAKSU2 = 'Puoliso: Kansaneläkevakuutusmaksu kotitalousvähennyksen jälkeen'
PKIRKOLLISVERO2 = 'Puoliso: Kirkollisvero kotitalousvähennyksen jälkeen'
PPAAOMAVERO2 = 'Puoliso: Pääomatulon vero kotitalousvähennyksen jälkeen'

PVALTTULOANSVERO3 = 'Puoliso: Ansiotulojen valtionvero alijäämähyvityksen jälkeen'
PKUNNALLISVERO3 = 'Puoliso: Kunnallisvero alijäämähyvityksen jälkeen'
PSAIRAUSVAKUUTUSMAKSU3 = 'Puoliso: Sairausvakuutusmaksu alijäämähyvityksen jälkeen'
PKELAVAKUUTUSMAKSU3 = 'Puoliso: Kansaneläkevakuutusmaksu alijäämähyvityksen jälkeen'
PKIRKOLLISVERO3 = 'Puoliso: Kirkollisvero alijäämähyvityksen jälkeen'

PVALTTULOANSVERO4 = 'Puoliso: Ansiotulojen valtionvero erityisen alijäämähyvityksen jälkeen'
PKUNNALLISVERO4 = 'Puoliso: Kunnallisvero erityisen alijäämähyvityksen jälkeen'
PSAIRAUSVAKUUTUSMAKSU4 = 'Puoliso: Sairausvakuutusmaksu erityisen alijäämähyvityksen jälkeen'
PKELAVAKUUTUSMAKSU4 = 'Puoliso: Kansaneläkevakuutusmaksu erityisen alijäämähyvityksen jälkeen'
PKIRKOLLISVERO4 = 'Puoliso: Kirkollisvero erityisen alijäämähyvityksen jälkeen'

PANSTULVEROT = 'Puoliso: Ansiotulojen verot (1993–) tai tuloverot yhteensä'
PVAVERO = 'Puoliso: Varallisuusvero (1993-2005)'
PKAIKKIVEROT1 = 'Puoliso: Kaikki verot kattosäännön jälkeen'
PKAIKKIVEROT2 = 'Puoliso: Verot yhtiöveron hyvityksen ja valtionverotuksen ans.tuloväh. (ennen 2009) jälkeen'
PYLEVERO = 'Puoliso: Yle-vero (2013-)'
PKAIKKIVEROT3 = 'Puoliso: Kaikki verot (ml. palkansaajan vakmaksut ja Yle-vero)'
PVEROJENOSUUS = 'Puoliso: Verojen osuus tuloista, %'
PNETTOTULOT = 'Puoliso: Nettotulo'

PVALTIO = 'Puoliso: Veronsaajien osuudet: Valtio'
PKUNNAT = 'Puoliso: Veronsaajien osuudet: Kunnat'
PKELA = 'Puoliso: Veronsaajien osuudet: KELA'
PKIRKKO = 'Puoliso: Veronsaajien osuudet: Kirkko'
PELTTVAKLAIT = 'Puoliso: Veronsaajien osuudet: Eläke- ja työttömyysvakuutuslaitokset'
PVERONSYHT = 'Puoliso: Veronsaajien osuudet yhteensä'

BRUTTOTULOT = 'Puolisot yhteensä: Bruttotulot'
VEROTYHT = 'Puolisot yhteensä:  Verot'
VEROJENOSTUL = 'Puolisot yhteensä: Verojen osuus tuloista, %'
NETTULOT = 'Puolisot yhteensä: Nettotulot' 

%END;

INF = 'Inflaatiokorjauksessa käytettävä kerroin';

KEEP &VALITUT;

RUN;

%IF &EXCEL = 1 %THEN %DO;
	ODS HTML3 BODY = "&LEVY&KENO&HAKEM&KENO.TULOS&KENO.OUTPUT&KENO&TULOSNIMI_VE..xls" STYLE = MINIMAL;
%END;

PROC PRINT NOOBS LABEL DATA = OUTPUT.&TULOSNIMI_VE;
TITLE "ESIMERKKILASKELMA, VERO";
RUN;

%IF &EXCEL = 1 %THEN %DO;
	ODS HTML3 CLOSE;
%END;

%MEND Vero_Simuloi_MargVero;

%Vero_Simuloi_MargVero;
